/*
MUDBASESDK

Testing FunctionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mudbase

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_mudbase_FunctionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FunctionsAPIService FunctionsActivate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var functionId string

		resp, httpRes, err := apiClient.FunctionsAPI.FunctionsActivate(context.Background(), projectId, functionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsAPIService FunctionsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.FunctionsAPI.FunctionsCreate(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsAPIService FunctionsDeactivate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var functionId string

		resp, httpRes, err := apiClient.FunctionsAPI.FunctionsDeactivate(context.Background(), projectId, functionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsAPIService FunctionsDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var functionId string

		resp, httpRes, err := apiClient.FunctionsAPI.FunctionsDelete(context.Background(), projectId, functionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsAPIService FunctionsExecute", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var functionId string

		resp, httpRes, err := apiClient.FunctionsAPI.FunctionsExecute(context.Background(), projectId, functionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsAPIService FunctionsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var functionId string

		resp, httpRes, err := apiClient.FunctionsAPI.FunctionsGet(context.Background(), projectId, functionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsAPIService FunctionsGetLogs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var functionId string

		resp, httpRes, err := apiClient.FunctionsAPI.FunctionsGetLogs(context.Background(), projectId, functionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsAPIService FunctionsGetVersions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var functionId string

		resp, httpRes, err := apiClient.FunctionsAPI.FunctionsGetVersions(context.Background(), projectId, functionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsAPIService FunctionsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.FunctionsAPI.FunctionsList(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsAPIService FunctionsRetry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var functionId string
		var executionIndex int32

		resp, httpRes, err := apiClient.FunctionsAPI.FunctionsRetry(context.Background(), projectId, functionId, executionIndex).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsAPIService FunctionsRollback", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var functionId string

		resp, httpRes, err := apiClient.FunctionsAPI.FunctionsRollback(context.Background(), projectId, functionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsAPIService FunctionsSimulate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var functionId string

		resp, httpRes, err := apiClient.FunctionsAPI.FunctionsSimulate(context.Background(), projectId, functionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsAPIService FunctionsTriggerWebhook", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.FunctionsAPI.FunctionsTriggerWebhook(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsAPIService FunctionsUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var functionId string

		resp, httpRes, err := apiClient.FunctionsAPI.FunctionsUpdate(context.Background(), projectId, functionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
