/*
MUDBASESDK

Testing RolesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mudbase

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_mudbase_RolesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RolesAPIService AssignRole", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var userId string

		resp, httpRes, err := apiClient.RolesAPI.AssignRole(context.Background(), orgId, userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RolesAPIService CheckPermissions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var userId string

		resp, httpRes, err := apiClient.RolesAPI.CheckPermissions(context.Background(), orgId, userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RolesAPIService CreateRole", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		resp, httpRes, err := apiClient.RolesAPI.CreateRole(context.Background(), orgId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RolesAPIService DeleteRole", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var roleId string

		resp, httpRes, err := apiClient.RolesAPI.DeleteRole(context.Background(), orgId, roleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RolesAPIService GetRole", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var roleId string

		resp, httpRes, err := apiClient.RolesAPI.GetRole(context.Background(), orgId, roleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RolesAPIService GetUsersByRole", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var roleSlug string

		resp, httpRes, err := apiClient.RolesAPI.GetUsersByRole(context.Background(), orgId, roleSlug).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RolesAPIService ListRoles", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		resp, httpRes, err := apiClient.RolesAPI.ListRoles(context.Background(), orgId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RolesAPIService RemoveRole", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var userId string

		resp, httpRes, err := apiClient.RolesAPI.RemoveRole(context.Background(), orgId, userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RolesAPIService UpdateRole", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var roleId string

		resp, httpRes, err := apiClient.RolesAPI.UpdateRole(context.Background(), orgId, roleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
