/*
MUDBASESDK

Testing ChatAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mudbase

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_mudbase_ChatAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ChatAPIService ChatAddParticipant", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var chatId string

		resp, httpRes, err := apiClient.ChatAPI.ChatAddParticipant(context.Background(), projectId, chatId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatAPIService ChatAddReaction", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var chatId string
		var messageId string

		resp, httpRes, err := apiClient.ChatAPI.ChatAddReaction(context.Background(), projectId, chatId, messageId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatAPIService ChatCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.ChatAPI.ChatCreate(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatAPIService ChatDeleteMessage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var chatId string
		var messageId string

		resp, httpRes, err := apiClient.ChatAPI.ChatDeleteMessage(context.Background(), projectId, chatId, messageId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatAPIService ChatEditMessage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var chatId string
		var messageId string

		resp, httpRes, err := apiClient.ChatAPI.ChatEditMessage(context.Background(), projectId, chatId, messageId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatAPIService ChatGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var chatId string

		resp, httpRes, err := apiClient.ChatAPI.ChatGet(context.Background(), projectId, chatId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatAPIService ChatGetMessages", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var chatId string

		resp, httpRes, err := apiClient.ChatAPI.ChatGetMessages(context.Background(), projectId, chatId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatAPIService ChatList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.ChatAPI.ChatList(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatAPIService ChatMarkAsRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var chatId string

		resp, httpRes, err := apiClient.ChatAPI.ChatMarkAsRead(context.Background(), projectId, chatId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatAPIService ChatRemoveParticipant", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var chatId string

		resp, httpRes, err := apiClient.ChatAPI.ChatRemoveParticipant(context.Background(), projectId, chatId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatAPIService ChatRemoveReaction", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var chatId string
		var messageId string

		resp, httpRes, err := apiClient.ChatAPI.ChatRemoveReaction(context.Background(), projectId, chatId, messageId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatAPIService ChatSendMessage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var chatId string

		resp, httpRes, err := apiClient.ChatAPI.ChatSendMessage(context.Background(), projectId, chatId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
