/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.9
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the SystemStatusResponseDataStorage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemStatusResponseDataStorage{}

// SystemStatusResponseDataStorage struct for SystemStatusResponseDataStorage
type SystemStatusResponseDataStorage struct {
	Used *int32 `json:"used,omitempty"`
	Available *int32 `json:"available,omitempty"`
	Percentage *float32 `json:"percentage,omitempty"`
}

// NewSystemStatusResponseDataStorage instantiates a new SystemStatusResponseDataStorage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemStatusResponseDataStorage() *SystemStatusResponseDataStorage {
	this := SystemStatusResponseDataStorage{}
	return &this
}

// NewSystemStatusResponseDataStorageWithDefaults instantiates a new SystemStatusResponseDataStorage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemStatusResponseDataStorageWithDefaults() *SystemStatusResponseDataStorage {
	this := SystemStatusResponseDataStorage{}
	return &this
}

// GetUsed returns the Used field value if set, zero value otherwise.
func (o *SystemStatusResponseDataStorage) GetUsed() int32 {
	if o == nil || IsNil(o.Used) {
		var ret int32
		return ret
	}
	return *o.Used
}

// GetUsedOk returns a tuple with the Used field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatusResponseDataStorage) GetUsedOk() (*int32, bool) {
	if o == nil || IsNil(o.Used) {
		return nil, false
	}
	return o.Used, true
}

// HasUsed returns a boolean if a field has been set.
func (o *SystemStatusResponseDataStorage) HasUsed() bool {
	if o != nil && !IsNil(o.Used) {
		return true
	}

	return false
}

// SetUsed gets a reference to the given int32 and assigns it to the Used field.
func (o *SystemStatusResponseDataStorage) SetUsed(v int32) {
	o.Used = &v
}

// GetAvailable returns the Available field value if set, zero value otherwise.
func (o *SystemStatusResponseDataStorage) GetAvailable() int32 {
	if o == nil || IsNil(o.Available) {
		var ret int32
		return ret
	}
	return *o.Available
}

// GetAvailableOk returns a tuple with the Available field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatusResponseDataStorage) GetAvailableOk() (*int32, bool) {
	if o == nil || IsNil(o.Available) {
		return nil, false
	}
	return o.Available, true
}

// HasAvailable returns a boolean if a field has been set.
func (o *SystemStatusResponseDataStorage) HasAvailable() bool {
	if o != nil && !IsNil(o.Available) {
		return true
	}

	return false
}

// SetAvailable gets a reference to the given int32 and assigns it to the Available field.
func (o *SystemStatusResponseDataStorage) SetAvailable(v int32) {
	o.Available = &v
}

// GetPercentage returns the Percentage field value if set, zero value otherwise.
func (o *SystemStatusResponseDataStorage) GetPercentage() float32 {
	if o == nil || IsNil(o.Percentage) {
		var ret float32
		return ret
	}
	return *o.Percentage
}

// GetPercentageOk returns a tuple with the Percentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatusResponseDataStorage) GetPercentageOk() (*float32, bool) {
	if o == nil || IsNil(o.Percentage) {
		return nil, false
	}
	return o.Percentage, true
}

// HasPercentage returns a boolean if a field has been set.
func (o *SystemStatusResponseDataStorage) HasPercentage() bool {
	if o != nil && !IsNil(o.Percentage) {
		return true
	}

	return false
}

// SetPercentage gets a reference to the given float32 and assigns it to the Percentage field.
func (o *SystemStatusResponseDataStorage) SetPercentage(v float32) {
	o.Percentage = &v
}

func (o SystemStatusResponseDataStorage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemStatusResponseDataStorage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Used) {
		toSerialize["used"] = o.Used
	}
	if !IsNil(o.Available) {
		toSerialize["available"] = o.Available
	}
	if !IsNil(o.Percentage) {
		toSerialize["percentage"] = o.Percentage
	}
	return toSerialize, nil
}

type NullableSystemStatusResponseDataStorage struct {
	value *SystemStatusResponseDataStorage
	isSet bool
}

func (v NullableSystemStatusResponseDataStorage) Get() *SystemStatusResponseDataStorage {
	return v.value
}

func (v *NullableSystemStatusResponseDataStorage) Set(val *SystemStatusResponseDataStorage) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemStatusResponseDataStorage) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemStatusResponseDataStorage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemStatusResponseDataStorage(val *SystemStatusResponseDataStorage) *NullableSystemStatusResponseDataStorage {
	return &NullableSystemStatusResponseDataStorage{value: val, isSet: true}
}

func (v NullableSystemStatusResponseDataStorage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemStatusResponseDataStorage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


