/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.3
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the SimulateAppPermissions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SimulateAppPermissions200Response{}

// SimulateAppPermissions200Response struct for SimulateAppPermissions200Response
type SimulateAppPermissions200Response struct {
	Success *bool `json:"success,omitempty"`
	Allowed *bool `json:"allowed,omitempty"`
	Reason *string `json:"reason,omitempty"`
	Evaluated *SimulateAppPermissions200ResponseEvaluated `json:"evaluated,omitempty"`
}

// NewSimulateAppPermissions200Response instantiates a new SimulateAppPermissions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSimulateAppPermissions200Response() *SimulateAppPermissions200Response {
	this := SimulateAppPermissions200Response{}
	return &this
}

// NewSimulateAppPermissions200ResponseWithDefaults instantiates a new SimulateAppPermissions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSimulateAppPermissions200ResponseWithDefaults() *SimulateAppPermissions200Response {
	this := SimulateAppPermissions200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *SimulateAppPermissions200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimulateAppPermissions200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *SimulateAppPermissions200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *SimulateAppPermissions200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetAllowed returns the Allowed field value if set, zero value otherwise.
func (o *SimulateAppPermissions200Response) GetAllowed() bool {
	if o == nil || IsNil(o.Allowed) {
		var ret bool
		return ret
	}
	return *o.Allowed
}

// GetAllowedOk returns a tuple with the Allowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimulateAppPermissions200Response) GetAllowedOk() (*bool, bool) {
	if o == nil || IsNil(o.Allowed) {
		return nil, false
	}
	return o.Allowed, true
}

// HasAllowed returns a boolean if a field has been set.
func (o *SimulateAppPermissions200Response) HasAllowed() bool {
	if o != nil && !IsNil(o.Allowed) {
		return true
	}

	return false
}

// SetAllowed gets a reference to the given bool and assigns it to the Allowed field.
func (o *SimulateAppPermissions200Response) SetAllowed(v bool) {
	o.Allowed = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *SimulateAppPermissions200Response) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimulateAppPermissions200Response) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *SimulateAppPermissions200Response) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *SimulateAppPermissions200Response) SetReason(v string) {
	o.Reason = &v
}

// GetEvaluated returns the Evaluated field value if set, zero value otherwise.
func (o *SimulateAppPermissions200Response) GetEvaluated() SimulateAppPermissions200ResponseEvaluated {
	if o == nil || IsNil(o.Evaluated) {
		var ret SimulateAppPermissions200ResponseEvaluated
		return ret
	}
	return *o.Evaluated
}

// GetEvaluatedOk returns a tuple with the Evaluated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimulateAppPermissions200Response) GetEvaluatedOk() (*SimulateAppPermissions200ResponseEvaluated, bool) {
	if o == nil || IsNil(o.Evaluated) {
		return nil, false
	}
	return o.Evaluated, true
}

// HasEvaluated returns a boolean if a field has been set.
func (o *SimulateAppPermissions200Response) HasEvaluated() bool {
	if o != nil && !IsNil(o.Evaluated) {
		return true
	}

	return false
}

// SetEvaluated gets a reference to the given SimulateAppPermissions200ResponseEvaluated and assigns it to the Evaluated field.
func (o *SimulateAppPermissions200Response) SetEvaluated(v SimulateAppPermissions200ResponseEvaluated) {
	o.Evaluated = &v
}

func (o SimulateAppPermissions200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SimulateAppPermissions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Allowed) {
		toSerialize["allowed"] = o.Allowed
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.Evaluated) {
		toSerialize["evaluated"] = o.Evaluated
	}
	return toSerialize, nil
}

type NullableSimulateAppPermissions200Response struct {
	value *SimulateAppPermissions200Response
	isSet bool
}

func (v NullableSimulateAppPermissions200Response) Get() *SimulateAppPermissions200Response {
	return v.value
}

func (v *NullableSimulateAppPermissions200Response) Set(val *SimulateAppPermissions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSimulateAppPermissions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSimulateAppPermissions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSimulateAppPermissions200Response(val *SimulateAppPermissions200Response) *NullableSimulateAppPermissions200Response {
	return &NullableSimulateAppPermissions200Response{value: val, isSet: true}
}

func (v NullableSimulateAppPermissions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSimulateAppPermissions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


