/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise: custom domains under `GET/POST/PATCH/DELETE /api/orgs/{orgId}/projects/{projectId}/domains` (plan `features.customDomainAllowed`); stable error codes `hostname_in_use`, `domain_limit_reached`, `domain_rate_limited`, `custom_domain_not_allowed`, `provision_conflict`, `not_enterprise_plan`; internal `POST /internal/provision-enterprise` with header `X-Internal-Api-Key`; responses on platform host may include `X-Mudbase-Warning: use_dedicated_api` for dedicated orgs. 

API version: 1.2.10
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the TwoFASetupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TwoFASetupResponse{}

// TwoFASetupResponse 2FA setup data (secret, QR code URL, manual entry key).
type TwoFASetupResponse struct {
	Secret *string `json:"secret,omitempty"`
	QrCode *string `json:"qrCode,omitempty"`
	ManualEntryKey *string `json:"manualEntryKey,omitempty"`
}

// NewTwoFASetupResponse instantiates a new TwoFASetupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTwoFASetupResponse() *TwoFASetupResponse {
	this := TwoFASetupResponse{}
	return &this
}

// NewTwoFASetupResponseWithDefaults instantiates a new TwoFASetupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTwoFASetupResponseWithDefaults() *TwoFASetupResponse {
	this := TwoFASetupResponse{}
	return &this
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *TwoFASetupResponse) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFASetupResponse) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *TwoFASetupResponse) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *TwoFASetupResponse) SetSecret(v string) {
	o.Secret = &v
}

// GetQrCode returns the QrCode field value if set, zero value otherwise.
func (o *TwoFASetupResponse) GetQrCode() string {
	if o == nil || IsNil(o.QrCode) {
		var ret string
		return ret
	}
	return *o.QrCode
}

// GetQrCodeOk returns a tuple with the QrCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFASetupResponse) GetQrCodeOk() (*string, bool) {
	if o == nil || IsNil(o.QrCode) {
		return nil, false
	}
	return o.QrCode, true
}

// HasQrCode returns a boolean if a field has been set.
func (o *TwoFASetupResponse) HasQrCode() bool {
	if o != nil && !IsNil(o.QrCode) {
		return true
	}

	return false
}

// SetQrCode gets a reference to the given string and assigns it to the QrCode field.
func (o *TwoFASetupResponse) SetQrCode(v string) {
	o.QrCode = &v
}

// GetManualEntryKey returns the ManualEntryKey field value if set, zero value otherwise.
func (o *TwoFASetupResponse) GetManualEntryKey() string {
	if o == nil || IsNil(o.ManualEntryKey) {
		var ret string
		return ret
	}
	return *o.ManualEntryKey
}

// GetManualEntryKeyOk returns a tuple with the ManualEntryKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFASetupResponse) GetManualEntryKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ManualEntryKey) {
		return nil, false
	}
	return o.ManualEntryKey, true
}

// HasManualEntryKey returns a boolean if a field has been set.
func (o *TwoFASetupResponse) HasManualEntryKey() bool {
	if o != nil && !IsNil(o.ManualEntryKey) {
		return true
	}

	return false
}

// SetManualEntryKey gets a reference to the given string and assigns it to the ManualEntryKey field.
func (o *TwoFASetupResponse) SetManualEntryKey(v string) {
	o.ManualEntryKey = &v
}

func (o TwoFASetupResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TwoFASetupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	if !IsNil(o.QrCode) {
		toSerialize["qrCode"] = o.QrCode
	}
	if !IsNil(o.ManualEntryKey) {
		toSerialize["manualEntryKey"] = o.ManualEntryKey
	}
	return toSerialize, nil
}

type NullableTwoFASetupResponse struct {
	value *TwoFASetupResponse
	isSet bool
}

func (v NullableTwoFASetupResponse) Get() *TwoFASetupResponse {
	return v.value
}

func (v *NullableTwoFASetupResponse) Set(val *TwoFASetupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTwoFASetupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTwoFASetupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTwoFASetupResponse(val *TwoFASetupResponse) *NullableTwoFASetupResponse {
	return &NullableTwoFASetupResponse{value: val, isSet: true}
}

func (v NullableTwoFASetupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTwoFASetupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


