/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.10
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the ValidateAddress200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateAddress200ResponseData{}

// ValidateAddress200ResponseData struct for ValidateAddress200ResponseData
type ValidateAddress200ResponseData struct {
	IsValid *bool `json:"isValid,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Address *string `json:"address,omitempty"`
}

// NewValidateAddress200ResponseData instantiates a new ValidateAddress200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateAddress200ResponseData() *ValidateAddress200ResponseData {
	this := ValidateAddress200ResponseData{}
	return &this
}

// NewValidateAddress200ResponseDataWithDefaults instantiates a new ValidateAddress200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateAddress200ResponseDataWithDefaults() *ValidateAddress200ResponseData {
	this := ValidateAddress200ResponseData{}
	return &this
}

// GetIsValid returns the IsValid field value if set, zero value otherwise.
func (o *ValidateAddress200ResponseData) GetIsValid() bool {
	if o == nil || IsNil(o.IsValid) {
		var ret bool
		return ret
	}
	return *o.IsValid
}

// GetIsValidOk returns a tuple with the IsValid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidateAddress200ResponseData) GetIsValidOk() (*bool, bool) {
	if o == nil || IsNil(o.IsValid) {
		return nil, false
	}
	return o.IsValid, true
}

// HasIsValid returns a boolean if a field has been set.
func (o *ValidateAddress200ResponseData) HasIsValid() bool {
	if o != nil && !IsNil(o.IsValid) {
		return true
	}

	return false
}

// SetIsValid gets a reference to the given bool and assigns it to the IsValid field.
func (o *ValidateAddress200ResponseData) SetIsValid(v bool) {
	o.IsValid = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ValidateAddress200ResponseData) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidateAddress200ResponseData) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ValidateAddress200ResponseData) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *ValidateAddress200ResponseData) SetCurrency(v string) {
	o.Currency = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *ValidateAddress200ResponseData) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidateAddress200ResponseData) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *ValidateAddress200ResponseData) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *ValidateAddress200ResponseData) SetAddress(v string) {
	o.Address = &v
}

func (o ValidateAddress200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateAddress200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsValid) {
		toSerialize["isValid"] = o.IsValid
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	return toSerialize, nil
}

type NullableValidateAddress200ResponseData struct {
	value *ValidateAddress200ResponseData
	isSet bool
}

func (v NullableValidateAddress200ResponseData) Get() *ValidateAddress200ResponseData {
	return v.value
}

func (v *NullableValidateAddress200ResponseData) Set(val *ValidateAddress200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateAddress200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateAddress200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateAddress200ResponseData(val *ValidateAddress200ResponseData) *NullableValidateAddress200ResponseData {
	return &NullableValidateAddress200ResponseData{value: val, isSet: true}
}

func (v NullableValidateAddress200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateAddress200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


