/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.4
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the MonitoringPerformanceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MonitoringPerformanceResponse{}

// MonitoringPerformanceResponse struct for MonitoringPerformanceResponse
type MonitoringPerformanceResponse struct {
	Period *string `json:"period,omitempty"`
	Metrics *MonitoringPerformanceResponseMetrics `json:"metrics,omitempty"`
	TopEndpoints []map[string]interface{} `json:"topEndpoints,omitempty"`
}

// NewMonitoringPerformanceResponse instantiates a new MonitoringPerformanceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMonitoringPerformanceResponse() *MonitoringPerformanceResponse {
	this := MonitoringPerformanceResponse{}
	return &this
}

// NewMonitoringPerformanceResponseWithDefaults instantiates a new MonitoringPerformanceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMonitoringPerformanceResponseWithDefaults() *MonitoringPerformanceResponse {
	this := MonitoringPerformanceResponse{}
	return &this
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *MonitoringPerformanceResponse) GetPeriod() string {
	if o == nil || IsNil(o.Period) {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonitoringPerformanceResponse) GetPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *MonitoringPerformanceResponse) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *MonitoringPerformanceResponse) SetPeriod(v string) {
	o.Period = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *MonitoringPerformanceResponse) GetMetrics() MonitoringPerformanceResponseMetrics {
	if o == nil || IsNil(o.Metrics) {
		var ret MonitoringPerformanceResponseMetrics
		return ret
	}
	return *o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonitoringPerformanceResponse) GetMetricsOk() (*MonitoringPerformanceResponseMetrics, bool) {
	if o == nil || IsNil(o.Metrics) {
		return nil, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *MonitoringPerformanceResponse) HasMetrics() bool {
	if o != nil && !IsNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given MonitoringPerformanceResponseMetrics and assigns it to the Metrics field.
func (o *MonitoringPerformanceResponse) SetMetrics(v MonitoringPerformanceResponseMetrics) {
	o.Metrics = &v
}

// GetTopEndpoints returns the TopEndpoints field value if set, zero value otherwise.
func (o *MonitoringPerformanceResponse) GetTopEndpoints() []map[string]interface{} {
	if o == nil || IsNil(o.TopEndpoints) {
		var ret []map[string]interface{}
		return ret
	}
	return o.TopEndpoints
}

// GetTopEndpointsOk returns a tuple with the TopEndpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonitoringPerformanceResponse) GetTopEndpointsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.TopEndpoints) {
		return nil, false
	}
	return o.TopEndpoints, true
}

// HasTopEndpoints returns a boolean if a field has been set.
func (o *MonitoringPerformanceResponse) HasTopEndpoints() bool {
	if o != nil && !IsNil(o.TopEndpoints) {
		return true
	}

	return false
}

// SetTopEndpoints gets a reference to the given []map[string]interface{} and assigns it to the TopEndpoints field.
func (o *MonitoringPerformanceResponse) SetTopEndpoints(v []map[string]interface{}) {
	o.TopEndpoints = v
}

func (o MonitoringPerformanceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MonitoringPerformanceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	if !IsNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	if !IsNil(o.TopEndpoints) {
		toSerialize["topEndpoints"] = o.TopEndpoints
	}
	return toSerialize, nil
}

type NullableMonitoringPerformanceResponse struct {
	value *MonitoringPerformanceResponse
	isSet bool
}

func (v NullableMonitoringPerformanceResponse) Get() *MonitoringPerformanceResponse {
	return v.value
}

func (v *NullableMonitoringPerformanceResponse) Set(val *MonitoringPerformanceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMonitoringPerformanceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMonitoringPerformanceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMonitoringPerformanceResponse(val *MonitoringPerformanceResponse) *NullableMonitoringPerformanceResponse {
	return &NullableMonitoringPerformanceResponse{value: val, isSet: true}
}

func (v NullableMonitoringPerformanceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMonitoringPerformanceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


