/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.7
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the GetProjectFeeDashboard200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProjectFeeDashboard200ResponseData{}

// GetProjectFeeDashboard200ResponseData struct for GetProjectFeeDashboard200ResponseData
type GetProjectFeeDashboard200ResponseData struct {
	FeeSettings map[string]interface{} `json:"feeSettings,omitempty"`
	Balances []GetProjectFeeDashboard200ResponseDataBalancesInner `json:"balances,omitempty"`
	RecentPayouts []GetProjectFeeDashboard200ResponseDataRecentPayoutsInner `json:"recentPayouts,omitempty"`
	TotalEarned *float32 `json:"totalEarned,omitempty"`
}

// NewGetProjectFeeDashboard200ResponseData instantiates a new GetProjectFeeDashboard200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProjectFeeDashboard200ResponseData() *GetProjectFeeDashboard200ResponseData {
	this := GetProjectFeeDashboard200ResponseData{}
	return &this
}

// NewGetProjectFeeDashboard200ResponseDataWithDefaults instantiates a new GetProjectFeeDashboard200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProjectFeeDashboard200ResponseDataWithDefaults() *GetProjectFeeDashboard200ResponseData {
	this := GetProjectFeeDashboard200ResponseData{}
	return &this
}

// GetFeeSettings returns the FeeSettings field value if set, zero value otherwise.
func (o *GetProjectFeeDashboard200ResponseData) GetFeeSettings() map[string]interface{} {
	if o == nil || IsNil(o.FeeSettings) {
		var ret map[string]interface{}
		return ret
	}
	return o.FeeSettings
}

// GetFeeSettingsOk returns a tuple with the FeeSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectFeeDashboard200ResponseData) GetFeeSettingsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FeeSettings) {
		return map[string]interface{}{}, false
	}
	return o.FeeSettings, true
}

// HasFeeSettings returns a boolean if a field has been set.
func (o *GetProjectFeeDashboard200ResponseData) HasFeeSettings() bool {
	if o != nil && !IsNil(o.FeeSettings) {
		return true
	}

	return false
}

// SetFeeSettings gets a reference to the given map[string]interface{} and assigns it to the FeeSettings field.
func (o *GetProjectFeeDashboard200ResponseData) SetFeeSettings(v map[string]interface{}) {
	o.FeeSettings = v
}

// GetBalances returns the Balances field value if set, zero value otherwise.
func (o *GetProjectFeeDashboard200ResponseData) GetBalances() []GetProjectFeeDashboard200ResponseDataBalancesInner {
	if o == nil || IsNil(o.Balances) {
		var ret []GetProjectFeeDashboard200ResponseDataBalancesInner
		return ret
	}
	return o.Balances
}

// GetBalancesOk returns a tuple with the Balances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectFeeDashboard200ResponseData) GetBalancesOk() ([]GetProjectFeeDashboard200ResponseDataBalancesInner, bool) {
	if o == nil || IsNil(o.Balances) {
		return nil, false
	}
	return o.Balances, true
}

// HasBalances returns a boolean if a field has been set.
func (o *GetProjectFeeDashboard200ResponseData) HasBalances() bool {
	if o != nil && !IsNil(o.Balances) {
		return true
	}

	return false
}

// SetBalances gets a reference to the given []GetProjectFeeDashboard200ResponseDataBalancesInner and assigns it to the Balances field.
func (o *GetProjectFeeDashboard200ResponseData) SetBalances(v []GetProjectFeeDashboard200ResponseDataBalancesInner) {
	o.Balances = v
}

// GetRecentPayouts returns the RecentPayouts field value if set, zero value otherwise.
func (o *GetProjectFeeDashboard200ResponseData) GetRecentPayouts() []GetProjectFeeDashboard200ResponseDataRecentPayoutsInner {
	if o == nil || IsNil(o.RecentPayouts) {
		var ret []GetProjectFeeDashboard200ResponseDataRecentPayoutsInner
		return ret
	}
	return o.RecentPayouts
}

// GetRecentPayoutsOk returns a tuple with the RecentPayouts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectFeeDashboard200ResponseData) GetRecentPayoutsOk() ([]GetProjectFeeDashboard200ResponseDataRecentPayoutsInner, bool) {
	if o == nil || IsNil(o.RecentPayouts) {
		return nil, false
	}
	return o.RecentPayouts, true
}

// HasRecentPayouts returns a boolean if a field has been set.
func (o *GetProjectFeeDashboard200ResponseData) HasRecentPayouts() bool {
	if o != nil && !IsNil(o.RecentPayouts) {
		return true
	}

	return false
}

// SetRecentPayouts gets a reference to the given []GetProjectFeeDashboard200ResponseDataRecentPayoutsInner and assigns it to the RecentPayouts field.
func (o *GetProjectFeeDashboard200ResponseData) SetRecentPayouts(v []GetProjectFeeDashboard200ResponseDataRecentPayoutsInner) {
	o.RecentPayouts = v
}

// GetTotalEarned returns the TotalEarned field value if set, zero value otherwise.
func (o *GetProjectFeeDashboard200ResponseData) GetTotalEarned() float32 {
	if o == nil || IsNil(o.TotalEarned) {
		var ret float32
		return ret
	}
	return *o.TotalEarned
}

// GetTotalEarnedOk returns a tuple with the TotalEarned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectFeeDashboard200ResponseData) GetTotalEarnedOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalEarned) {
		return nil, false
	}
	return o.TotalEarned, true
}

// HasTotalEarned returns a boolean if a field has been set.
func (o *GetProjectFeeDashboard200ResponseData) HasTotalEarned() bool {
	if o != nil && !IsNil(o.TotalEarned) {
		return true
	}

	return false
}

// SetTotalEarned gets a reference to the given float32 and assigns it to the TotalEarned field.
func (o *GetProjectFeeDashboard200ResponseData) SetTotalEarned(v float32) {
	o.TotalEarned = &v
}

func (o GetProjectFeeDashboard200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProjectFeeDashboard200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FeeSettings) {
		toSerialize["feeSettings"] = o.FeeSettings
	}
	if !IsNil(o.Balances) {
		toSerialize["balances"] = o.Balances
	}
	if !IsNil(o.RecentPayouts) {
		toSerialize["recentPayouts"] = o.RecentPayouts
	}
	if !IsNil(o.TotalEarned) {
		toSerialize["totalEarned"] = o.TotalEarned
	}
	return toSerialize, nil
}

type NullableGetProjectFeeDashboard200ResponseData struct {
	value *GetProjectFeeDashboard200ResponseData
	isSet bool
}

func (v NullableGetProjectFeeDashboard200ResponseData) Get() *GetProjectFeeDashboard200ResponseData {
	return v.value
}

func (v *NullableGetProjectFeeDashboard200ResponseData) Set(val *GetProjectFeeDashboard200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProjectFeeDashboard200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProjectFeeDashboard200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProjectFeeDashboard200ResponseData(val *GetProjectFeeDashboard200ResponseData) *NullableGetProjectFeeDashboard200ResponseData {
	return &NullableGetProjectFeeDashboard200ResponseData{value: val, isSet: true}
}

func (v NullableGetProjectFeeDashboard200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProjectFeeDashboard200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


