/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.7
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
	"time"
)

// checks if the PaymentSubscription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentSubscription{}

// PaymentSubscription Subscription record (id, plan, status, currentPeriodEnd, etc.).
type PaymentSubscription struct {
	Id *string `json:"_id,omitempty"`
	// Merchant ID
	Merchant *string `json:"merchant,omitempty"`
	// Project ID
	Project *string `json:"project,omitempty"`
	// Subscription amount
	Amount *float32 `json:"amount,omitempty"`
	Interval *string `json:"interval,omitempty"`
	Network *string `json:"network,omitempty"`
	Token *string `json:"token,omitempty"`
	Status *string `json:"status,omitempty"`
	// Next payment due date
	NextPaymentAt *time.Time `json:"nextPaymentAt,omitempty"`
	// Grace period in days
	GracePeriodDays *int32 `json:"gracePeriodDays,omitempty"`
	EarlyPaymentAllowed *bool `json:"earlyPaymentAllowed,omitempty"`
	LatePaymentAllowed *bool `json:"latePaymentAllowed,omitempty"`
	ProrationEnabled *bool `json:"prorationEnabled,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewPaymentSubscription instantiates a new PaymentSubscription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentSubscription() *PaymentSubscription {
	this := PaymentSubscription{}
	var gracePeriodDays int32 = 3
	this.GracePeriodDays = &gracePeriodDays
	var earlyPaymentAllowed bool = true
	this.EarlyPaymentAllowed = &earlyPaymentAllowed
	var latePaymentAllowed bool = true
	this.LatePaymentAllowed = &latePaymentAllowed
	var prorationEnabled bool = false
	this.ProrationEnabled = &prorationEnabled
	return &this
}

// NewPaymentSubscriptionWithDefaults instantiates a new PaymentSubscription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentSubscriptionWithDefaults() *PaymentSubscription {
	this := PaymentSubscription{}
	var gracePeriodDays int32 = 3
	this.GracePeriodDays = &gracePeriodDays
	var earlyPaymentAllowed bool = true
	this.EarlyPaymentAllowed = &earlyPaymentAllowed
	var latePaymentAllowed bool = true
	this.LatePaymentAllowed = &latePaymentAllowed
	var prorationEnabled bool = false
	this.ProrationEnabled = &prorationEnabled
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PaymentSubscription) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PaymentSubscription) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PaymentSubscription) SetId(v string) {
	o.Id = &v
}

// GetMerchant returns the Merchant field value if set, zero value otherwise.
func (o *PaymentSubscription) GetMerchant() string {
	if o == nil || IsNil(o.Merchant) {
		var ret string
		return ret
	}
	return *o.Merchant
}

// GetMerchantOk returns a tuple with the Merchant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetMerchantOk() (*string, bool) {
	if o == nil || IsNil(o.Merchant) {
		return nil, false
	}
	return o.Merchant, true
}

// HasMerchant returns a boolean if a field has been set.
func (o *PaymentSubscription) HasMerchant() bool {
	if o != nil && !IsNil(o.Merchant) {
		return true
	}

	return false
}

// SetMerchant gets a reference to the given string and assigns it to the Merchant field.
func (o *PaymentSubscription) SetMerchant(v string) {
	o.Merchant = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *PaymentSubscription) GetProject() string {
	if o == nil || IsNil(o.Project) {
		var ret string
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetProjectOk() (*string, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *PaymentSubscription) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given string and assigns it to the Project field.
func (o *PaymentSubscription) SetProject(v string) {
	o.Project = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *PaymentSubscription) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *PaymentSubscription) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *PaymentSubscription) SetAmount(v float32) {
	o.Amount = &v
}

// GetInterval returns the Interval field value if set, zero value otherwise.
func (o *PaymentSubscription) GetInterval() string {
	if o == nil || IsNil(o.Interval) {
		var ret string
		return ret
	}
	return *o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.Interval) {
		return nil, false
	}
	return o.Interval, true
}

// HasInterval returns a boolean if a field has been set.
func (o *PaymentSubscription) HasInterval() bool {
	if o != nil && !IsNil(o.Interval) {
		return true
	}

	return false
}

// SetInterval gets a reference to the given string and assigns it to the Interval field.
func (o *PaymentSubscription) SetInterval(v string) {
	o.Interval = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *PaymentSubscription) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *PaymentSubscription) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *PaymentSubscription) SetNetwork(v string) {
	o.Network = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *PaymentSubscription) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *PaymentSubscription) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *PaymentSubscription) SetToken(v string) {
	o.Token = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PaymentSubscription) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PaymentSubscription) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PaymentSubscription) SetStatus(v string) {
	o.Status = &v
}

// GetNextPaymentAt returns the NextPaymentAt field value if set, zero value otherwise.
func (o *PaymentSubscription) GetNextPaymentAt() time.Time {
	if o == nil || IsNil(o.NextPaymentAt) {
		var ret time.Time
		return ret
	}
	return *o.NextPaymentAt
}

// GetNextPaymentAtOk returns a tuple with the NextPaymentAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetNextPaymentAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.NextPaymentAt) {
		return nil, false
	}
	return o.NextPaymentAt, true
}

// HasNextPaymentAt returns a boolean if a field has been set.
func (o *PaymentSubscription) HasNextPaymentAt() bool {
	if o != nil && !IsNil(o.NextPaymentAt) {
		return true
	}

	return false
}

// SetNextPaymentAt gets a reference to the given time.Time and assigns it to the NextPaymentAt field.
func (o *PaymentSubscription) SetNextPaymentAt(v time.Time) {
	o.NextPaymentAt = &v
}

// GetGracePeriodDays returns the GracePeriodDays field value if set, zero value otherwise.
func (o *PaymentSubscription) GetGracePeriodDays() int32 {
	if o == nil || IsNil(o.GracePeriodDays) {
		var ret int32
		return ret
	}
	return *o.GracePeriodDays
}

// GetGracePeriodDaysOk returns a tuple with the GracePeriodDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetGracePeriodDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.GracePeriodDays) {
		return nil, false
	}
	return o.GracePeriodDays, true
}

// HasGracePeriodDays returns a boolean if a field has been set.
func (o *PaymentSubscription) HasGracePeriodDays() bool {
	if o != nil && !IsNil(o.GracePeriodDays) {
		return true
	}

	return false
}

// SetGracePeriodDays gets a reference to the given int32 and assigns it to the GracePeriodDays field.
func (o *PaymentSubscription) SetGracePeriodDays(v int32) {
	o.GracePeriodDays = &v
}

// GetEarlyPaymentAllowed returns the EarlyPaymentAllowed field value if set, zero value otherwise.
func (o *PaymentSubscription) GetEarlyPaymentAllowed() bool {
	if o == nil || IsNil(o.EarlyPaymentAllowed) {
		var ret bool
		return ret
	}
	return *o.EarlyPaymentAllowed
}

// GetEarlyPaymentAllowedOk returns a tuple with the EarlyPaymentAllowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetEarlyPaymentAllowedOk() (*bool, bool) {
	if o == nil || IsNil(o.EarlyPaymentAllowed) {
		return nil, false
	}
	return o.EarlyPaymentAllowed, true
}

// HasEarlyPaymentAllowed returns a boolean if a field has been set.
func (o *PaymentSubscription) HasEarlyPaymentAllowed() bool {
	if o != nil && !IsNil(o.EarlyPaymentAllowed) {
		return true
	}

	return false
}

// SetEarlyPaymentAllowed gets a reference to the given bool and assigns it to the EarlyPaymentAllowed field.
func (o *PaymentSubscription) SetEarlyPaymentAllowed(v bool) {
	o.EarlyPaymentAllowed = &v
}

// GetLatePaymentAllowed returns the LatePaymentAllowed field value if set, zero value otherwise.
func (o *PaymentSubscription) GetLatePaymentAllowed() bool {
	if o == nil || IsNil(o.LatePaymentAllowed) {
		var ret bool
		return ret
	}
	return *o.LatePaymentAllowed
}

// GetLatePaymentAllowedOk returns a tuple with the LatePaymentAllowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetLatePaymentAllowedOk() (*bool, bool) {
	if o == nil || IsNil(o.LatePaymentAllowed) {
		return nil, false
	}
	return o.LatePaymentAllowed, true
}

// HasLatePaymentAllowed returns a boolean if a field has been set.
func (o *PaymentSubscription) HasLatePaymentAllowed() bool {
	if o != nil && !IsNil(o.LatePaymentAllowed) {
		return true
	}

	return false
}

// SetLatePaymentAllowed gets a reference to the given bool and assigns it to the LatePaymentAllowed field.
func (o *PaymentSubscription) SetLatePaymentAllowed(v bool) {
	o.LatePaymentAllowed = &v
}

// GetProrationEnabled returns the ProrationEnabled field value if set, zero value otherwise.
func (o *PaymentSubscription) GetProrationEnabled() bool {
	if o == nil || IsNil(o.ProrationEnabled) {
		var ret bool
		return ret
	}
	return *o.ProrationEnabled
}

// GetProrationEnabledOk returns a tuple with the ProrationEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetProrationEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ProrationEnabled) {
		return nil, false
	}
	return o.ProrationEnabled, true
}

// HasProrationEnabled returns a boolean if a field has been set.
func (o *PaymentSubscription) HasProrationEnabled() bool {
	if o != nil && !IsNil(o.ProrationEnabled) {
		return true
	}

	return false
}

// SetProrationEnabled gets a reference to the given bool and assigns it to the ProrationEnabled field.
func (o *PaymentSubscription) SetProrationEnabled(v bool) {
	o.ProrationEnabled = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *PaymentSubscription) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PaymentSubscription) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *PaymentSubscription) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *PaymentSubscription) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentSubscription) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *PaymentSubscription) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *PaymentSubscription) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o PaymentSubscription) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentSubscription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["_id"] = o.Id
	}
	if !IsNil(o.Merchant) {
		toSerialize["merchant"] = o.Merchant
	}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Interval) {
		toSerialize["interval"] = o.Interval
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.NextPaymentAt) {
		toSerialize["nextPaymentAt"] = o.NextPaymentAt
	}
	if !IsNil(o.GracePeriodDays) {
		toSerialize["gracePeriodDays"] = o.GracePeriodDays
	}
	if !IsNil(o.EarlyPaymentAllowed) {
		toSerialize["earlyPaymentAllowed"] = o.EarlyPaymentAllowed
	}
	if !IsNil(o.LatePaymentAllowed) {
		toSerialize["latePaymentAllowed"] = o.LatePaymentAllowed
	}
	if !IsNil(o.ProrationEnabled) {
		toSerialize["prorationEnabled"] = o.ProrationEnabled
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullablePaymentSubscription struct {
	value *PaymentSubscription
	isSet bool
}

func (v NullablePaymentSubscription) Get() *PaymentSubscription {
	return v.value
}

func (v *NullablePaymentSubscription) Set(val *PaymentSubscription) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentSubscription) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentSubscription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentSubscription(val *PaymentSubscription) *NullablePaymentSubscription {
	return &NullablePaymentSubscription{value: val, isSet: true}
}

func (v NullablePaymentSubscription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentSubscription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


