/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.4
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterWithRoleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterWithRoleRequest{}

// RegisterWithRoleRequest struct for RegisterWithRoleRequest
type RegisterWithRoleRequest struct {
	Email string `json:"email"`
	Password string `json:"password"`
	FirstName string `json:"firstName"`
	LastName string `json:"lastName"`
	ProjectId string `json:"projectId"`
	// Must be `true` - the server rejects the request otherwise. Required to stop a direct API call from creating an account without accepting the Terms of Service and Privacy Policy.
	AgreedToTerms bool `json:"agreedToTerms"`
}

type _RegisterWithRoleRequest RegisterWithRoleRequest

// NewRegisterWithRoleRequest instantiates a new RegisterWithRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterWithRoleRequest(email string, password string, firstName string, lastName string, projectId string, agreedToTerms bool) *RegisterWithRoleRequest {
	this := RegisterWithRoleRequest{}
	this.Email = email
	this.Password = password
	this.FirstName = firstName
	this.LastName = lastName
	this.ProjectId = projectId
	this.AgreedToTerms = agreedToTerms
	return &this
}

// NewRegisterWithRoleRequestWithDefaults instantiates a new RegisterWithRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterWithRoleRequestWithDefaults() *RegisterWithRoleRequest {
	this := RegisterWithRoleRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *RegisterWithRoleRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *RegisterWithRoleRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *RegisterWithRoleRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *RegisterWithRoleRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *RegisterWithRoleRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *RegisterWithRoleRequest) SetPassword(v string) {
	o.Password = v
}

// GetFirstName returns the FirstName field value
func (o *RegisterWithRoleRequest) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *RegisterWithRoleRequest) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *RegisterWithRoleRequest) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value
func (o *RegisterWithRoleRequest) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *RegisterWithRoleRequest) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *RegisterWithRoleRequest) SetLastName(v string) {
	o.LastName = v
}

// GetProjectId returns the ProjectId field value
func (o *RegisterWithRoleRequest) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *RegisterWithRoleRequest) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *RegisterWithRoleRequest) SetProjectId(v string) {
	o.ProjectId = v
}

// GetAgreedToTerms returns the AgreedToTerms field value
func (o *RegisterWithRoleRequest) GetAgreedToTerms() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AgreedToTerms
}

// GetAgreedToTermsOk returns a tuple with the AgreedToTerms field value
// and a boolean to check if the value has been set.
func (o *RegisterWithRoleRequest) GetAgreedToTermsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgreedToTerms, true
}

// SetAgreedToTerms sets field value
func (o *RegisterWithRoleRequest) SetAgreedToTerms(v bool) {
	o.AgreedToTerms = v
}

func (o RegisterWithRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterWithRoleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	toSerialize["firstName"] = o.FirstName
	toSerialize["lastName"] = o.LastName
	toSerialize["projectId"] = o.ProjectId
	toSerialize["agreedToTerms"] = o.AgreedToTerms
	return toSerialize, nil
}

func (o *RegisterWithRoleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
		"firstName",
		"lastName",
		"projectId",
		"agreedToTerms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterWithRoleRequest := _RegisterWithRoleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterWithRoleRequest)

	if err != nil {
		return err
	}

	*o = RegisterWithRoleRequest(varRegisterWithRoleRequest)

	return err
}

type NullableRegisterWithRoleRequest struct {
	value *RegisterWithRoleRequest
	isSet bool
}

func (v NullableRegisterWithRoleRequest) Get() *RegisterWithRoleRequest {
	return v.value
}

func (v *NullableRegisterWithRoleRequest) Set(val *RegisterWithRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterWithRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterWithRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterWithRoleRequest(val *RegisterWithRoleRequest) *NullableRegisterWithRoleRequest {
	return &NullableRegisterWithRoleRequest{value: val, isSet: true}
}

func (v NullableRegisterWithRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterWithRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


