/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.10
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GenerateAccessReviewRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateAccessReviewRequest{}

// GenerateAccessReviewRequest struct for GenerateAccessReviewRequest
type GenerateAccessReviewRequest struct {
	OrgId string `json:"orgId"`
	ReviewPeriod GenerateAccessReviewRequestReviewPeriod `json:"reviewPeriod"`
}

type _GenerateAccessReviewRequest GenerateAccessReviewRequest

// NewGenerateAccessReviewRequest instantiates a new GenerateAccessReviewRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateAccessReviewRequest(orgId string, reviewPeriod GenerateAccessReviewRequestReviewPeriod) *GenerateAccessReviewRequest {
	this := GenerateAccessReviewRequest{}
	this.OrgId = orgId
	this.ReviewPeriod = reviewPeriod
	return &this
}

// NewGenerateAccessReviewRequestWithDefaults instantiates a new GenerateAccessReviewRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateAccessReviewRequestWithDefaults() *GenerateAccessReviewRequest {
	this := GenerateAccessReviewRequest{}
	return &this
}

// GetOrgId returns the OrgId field value
func (o *GenerateAccessReviewRequest) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *GenerateAccessReviewRequest) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *GenerateAccessReviewRequest) SetOrgId(v string) {
	o.OrgId = v
}

// GetReviewPeriod returns the ReviewPeriod field value
func (o *GenerateAccessReviewRequest) GetReviewPeriod() GenerateAccessReviewRequestReviewPeriod {
	if o == nil {
		var ret GenerateAccessReviewRequestReviewPeriod
		return ret
	}

	return o.ReviewPeriod
}

// GetReviewPeriodOk returns a tuple with the ReviewPeriod field value
// and a boolean to check if the value has been set.
func (o *GenerateAccessReviewRequest) GetReviewPeriodOk() (*GenerateAccessReviewRequestReviewPeriod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReviewPeriod, true
}

// SetReviewPeriod sets field value
func (o *GenerateAccessReviewRequest) SetReviewPeriod(v GenerateAccessReviewRequestReviewPeriod) {
	o.ReviewPeriod = v
}

func (o GenerateAccessReviewRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateAccessReviewRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["orgId"] = o.OrgId
	toSerialize["reviewPeriod"] = o.ReviewPeriod
	return toSerialize, nil
}

func (o *GenerateAccessReviewRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"orgId",
		"reviewPeriod",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGenerateAccessReviewRequest := _GenerateAccessReviewRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGenerateAccessReviewRequest)

	if err != nil {
		return err
	}

	*o = GenerateAccessReviewRequest(varGenerateAccessReviewRequest)

	return err
}

type NullableGenerateAccessReviewRequest struct {
	value *GenerateAccessReviewRequest
	isSet bool
}

func (v NullableGenerateAccessReviewRequest) Get() *GenerateAccessReviewRequest {
	return v.value
}

func (v *NullableGenerateAccessReviewRequest) Set(val *GenerateAccessReviewRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateAccessReviewRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateAccessReviewRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateAccessReviewRequest(val *GenerateAccessReviewRequest) *NullableGenerateAccessReviewRequest {
	return &NullableGenerateAccessReviewRequest{value: val, isSet: true}
}

func (v NullableGenerateAccessReviewRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateAccessReviewRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


