/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.8
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OTPVerifyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OTPVerifyRequest{}

// OTPVerifyRequest OTP code and identifier (phone/email) for verification.
type OTPVerifyRequest struct {
	Identifier *string `json:"identifier,omitempty"`
	Otp string `json:"otp"`
	ProjectId string `json:"projectId"`
}

type _OTPVerifyRequest OTPVerifyRequest

// NewOTPVerifyRequest instantiates a new OTPVerifyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOTPVerifyRequest(otp string, projectId string) *OTPVerifyRequest {
	this := OTPVerifyRequest{}
	this.Otp = otp
	this.ProjectId = projectId
	return &this
}

// NewOTPVerifyRequestWithDefaults instantiates a new OTPVerifyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOTPVerifyRequestWithDefaults() *OTPVerifyRequest {
	this := OTPVerifyRequest{}
	return &this
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *OTPVerifyRequest) GetIdentifier() string {
	if o == nil || IsNil(o.Identifier) {
		var ret string
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OTPVerifyRequest) GetIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.Identifier) {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *OTPVerifyRequest) HasIdentifier() bool {
	if o != nil && !IsNil(o.Identifier) {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given string and assigns it to the Identifier field.
func (o *OTPVerifyRequest) SetIdentifier(v string) {
	o.Identifier = &v
}

// GetOtp returns the Otp field value
func (o *OTPVerifyRequest) GetOtp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Otp
}

// GetOtpOk returns a tuple with the Otp field value
// and a boolean to check if the value has been set.
func (o *OTPVerifyRequest) GetOtpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Otp, true
}

// SetOtp sets field value
func (o *OTPVerifyRequest) SetOtp(v string) {
	o.Otp = v
}

// GetProjectId returns the ProjectId field value
func (o *OTPVerifyRequest) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *OTPVerifyRequest) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *OTPVerifyRequest) SetProjectId(v string) {
	o.ProjectId = v
}

func (o OTPVerifyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OTPVerifyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Identifier) {
		toSerialize["identifier"] = o.Identifier
	}
	toSerialize["otp"] = o.Otp
	toSerialize["projectId"] = o.ProjectId
	return toSerialize, nil
}

func (o *OTPVerifyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"otp",
		"projectId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOTPVerifyRequest := _OTPVerifyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOTPVerifyRequest)

	if err != nil {
		return err
	}

	*o = OTPVerifyRequest(varOTPVerifyRequest)

	return err
}

type NullableOTPVerifyRequest struct {
	value *OTPVerifyRequest
	isSet bool
}

func (v NullableOTPVerifyRequest) Get() *OTPVerifyRequest {
	return v.value
}

func (v *NullableOTPVerifyRequest) Set(val *OTPVerifyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOTPVerifyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOTPVerifyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOTPVerifyRequest(val *OTPVerifyRequest) *NullableOTPVerifyRequest {
	return &NullableOTPVerifyRequest{value: val, isSet: true}
}

func (v NullableOTPVerifyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOTPVerifyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


