/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.4
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the CalculateWalletFee200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalculateWalletFee200ResponseData{}

// CalculateWalletFee200ResponseData struct for CalculateWalletFee200ResponseData
type CalculateWalletFee200ResponseData struct {
	// Request currency / native currency for the chain
	Currency *string `json:"currency,omitempty"`
	Network NullableString `json:"network,omitempty"`
	Amount *float32 `json:"amount,omitempty"`
	// Chain id used for estimation
	Chain *string `json:"chain,omitempty"`
	// Human-readable network fee from blockchain
	NetworkFee *string `json:"networkFee,omitempty"`
	EstimatedTime *string `json:"estimatedTime,omitempty"`
	// Network congestion level (EVM from gas price; UTXO from sat/vB)
	Congestion *string `json:"congestion,omitempty"`
	// (EVM only) Gas limit
	GasLimit *string `json:"gasLimit,omitempty"`
	// (EVM only) Gas price in wei
	GasPrice *string `json:"gasPrice,omitempty"`
	// (EVM only) Gas price in Gwei
	GasPriceGwei *float32 `json:"gasPriceGwei,omitempty"`
	// (EVM only) Cost in wei
	EstimatedCost *string `json:"estimatedCost,omitempty"`
	// (UTXO only) Satoshis per vbyte
	SatPerVb *int32 `json:"satPerVb,omitempty"`
	// (UTXO only) Fee in satoshis
	FeeSat *int32 `json:"feeSat,omitempty"`
	// (Solana only) Fee in lamports
	Lamports *int32 `json:"lamports,omitempty"`
	// (EVM only) slow / normal / fast tiers; each has gasPriceGwei, networkFee
	FeeTiers *map[string]CalculateWalletFee200ResponseDataFeeTiersValue `json:"feeTiers,omitempty"`
	// True when current gas is ≥5× chain minimum (consider warning user)
	GasSpikeWarning *bool `json:"gasSpikeWarning,omitempty"`
}

// NewCalculateWalletFee200ResponseData instantiates a new CalculateWalletFee200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalculateWalletFee200ResponseData() *CalculateWalletFee200ResponseData {
	this := CalculateWalletFee200ResponseData{}
	return &this
}

// NewCalculateWalletFee200ResponseDataWithDefaults instantiates a new CalculateWalletFee200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalculateWalletFee200ResponseDataWithDefaults() *CalculateWalletFee200ResponseData {
	this := CalculateWalletFee200ResponseData{}
	return &this
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *CalculateWalletFee200ResponseData) SetCurrency(v string) {
	o.Currency = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CalculateWalletFee200ResponseData) GetNetwork() string {
	if o == nil || IsNil(o.Network.Get()) {
		var ret string
		return ret
	}
	return *o.Network.Get()
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CalculateWalletFee200ResponseData) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Network.Get(), o.Network.IsSet()
}

// HasNetwork returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasNetwork() bool {
	if o != nil && o.Network.IsSet() {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given NullableString and assigns it to the Network field.
func (o *CalculateWalletFee200ResponseData) SetNetwork(v string) {
	o.Network.Set(&v)
}
// SetNetworkNil sets the value for Network to be an explicit nil
func (o *CalculateWalletFee200ResponseData) SetNetworkNil() {
	o.Network.Set(nil)
}

// UnsetNetwork ensures that no value is present for Network, not even an explicit nil
func (o *CalculateWalletFee200ResponseData) UnsetNetwork() {
	o.Network.Unset()
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *CalculateWalletFee200ResponseData) SetAmount(v float32) {
	o.Amount = &v
}

// GetChain returns the Chain field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetChain() string {
	if o == nil || IsNil(o.Chain) {
		var ret string
		return ret
	}
	return *o.Chain
}

// GetChainOk returns a tuple with the Chain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetChainOk() (*string, bool) {
	if o == nil || IsNil(o.Chain) {
		return nil, false
	}
	return o.Chain, true
}

// HasChain returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasChain() bool {
	if o != nil && !IsNil(o.Chain) {
		return true
	}

	return false
}

// SetChain gets a reference to the given string and assigns it to the Chain field.
func (o *CalculateWalletFee200ResponseData) SetChain(v string) {
	o.Chain = &v
}

// GetNetworkFee returns the NetworkFee field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetNetworkFee() string {
	if o == nil || IsNil(o.NetworkFee) {
		var ret string
		return ret
	}
	return *o.NetworkFee
}

// GetNetworkFeeOk returns a tuple with the NetworkFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetNetworkFeeOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkFee) {
		return nil, false
	}
	return o.NetworkFee, true
}

// HasNetworkFee returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasNetworkFee() bool {
	if o != nil && !IsNil(o.NetworkFee) {
		return true
	}

	return false
}

// SetNetworkFee gets a reference to the given string and assigns it to the NetworkFee field.
func (o *CalculateWalletFee200ResponseData) SetNetworkFee(v string) {
	o.NetworkFee = &v
}

// GetEstimatedTime returns the EstimatedTime field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetEstimatedTime() string {
	if o == nil || IsNil(o.EstimatedTime) {
		var ret string
		return ret
	}
	return *o.EstimatedTime
}

// GetEstimatedTimeOk returns a tuple with the EstimatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetEstimatedTimeOk() (*string, bool) {
	if o == nil || IsNil(o.EstimatedTime) {
		return nil, false
	}
	return o.EstimatedTime, true
}

// HasEstimatedTime returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasEstimatedTime() bool {
	if o != nil && !IsNil(o.EstimatedTime) {
		return true
	}

	return false
}

// SetEstimatedTime gets a reference to the given string and assigns it to the EstimatedTime field.
func (o *CalculateWalletFee200ResponseData) SetEstimatedTime(v string) {
	o.EstimatedTime = &v
}

// GetCongestion returns the Congestion field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetCongestion() string {
	if o == nil || IsNil(o.Congestion) {
		var ret string
		return ret
	}
	return *o.Congestion
}

// GetCongestionOk returns a tuple with the Congestion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetCongestionOk() (*string, bool) {
	if o == nil || IsNil(o.Congestion) {
		return nil, false
	}
	return o.Congestion, true
}

// HasCongestion returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasCongestion() bool {
	if o != nil && !IsNil(o.Congestion) {
		return true
	}

	return false
}

// SetCongestion gets a reference to the given string and assigns it to the Congestion field.
func (o *CalculateWalletFee200ResponseData) SetCongestion(v string) {
	o.Congestion = &v
}

// GetGasLimit returns the GasLimit field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetGasLimit() string {
	if o == nil || IsNil(o.GasLimit) {
		var ret string
		return ret
	}
	return *o.GasLimit
}

// GetGasLimitOk returns a tuple with the GasLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetGasLimitOk() (*string, bool) {
	if o == nil || IsNil(o.GasLimit) {
		return nil, false
	}
	return o.GasLimit, true
}

// HasGasLimit returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasGasLimit() bool {
	if o != nil && !IsNil(o.GasLimit) {
		return true
	}

	return false
}

// SetGasLimit gets a reference to the given string and assigns it to the GasLimit field.
func (o *CalculateWalletFee200ResponseData) SetGasLimit(v string) {
	o.GasLimit = &v
}

// GetGasPrice returns the GasPrice field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetGasPrice() string {
	if o == nil || IsNil(o.GasPrice) {
		var ret string
		return ret
	}
	return *o.GasPrice
}

// GetGasPriceOk returns a tuple with the GasPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetGasPriceOk() (*string, bool) {
	if o == nil || IsNil(o.GasPrice) {
		return nil, false
	}
	return o.GasPrice, true
}

// HasGasPrice returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasGasPrice() bool {
	if o != nil && !IsNil(o.GasPrice) {
		return true
	}

	return false
}

// SetGasPrice gets a reference to the given string and assigns it to the GasPrice field.
func (o *CalculateWalletFee200ResponseData) SetGasPrice(v string) {
	o.GasPrice = &v
}

// GetGasPriceGwei returns the GasPriceGwei field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetGasPriceGwei() float32 {
	if o == nil || IsNil(o.GasPriceGwei) {
		var ret float32
		return ret
	}
	return *o.GasPriceGwei
}

// GetGasPriceGweiOk returns a tuple with the GasPriceGwei field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetGasPriceGweiOk() (*float32, bool) {
	if o == nil || IsNil(o.GasPriceGwei) {
		return nil, false
	}
	return o.GasPriceGwei, true
}

// HasGasPriceGwei returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasGasPriceGwei() bool {
	if o != nil && !IsNil(o.GasPriceGwei) {
		return true
	}

	return false
}

// SetGasPriceGwei gets a reference to the given float32 and assigns it to the GasPriceGwei field.
func (o *CalculateWalletFee200ResponseData) SetGasPriceGwei(v float32) {
	o.GasPriceGwei = &v
}

// GetEstimatedCost returns the EstimatedCost field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetEstimatedCost() string {
	if o == nil || IsNil(o.EstimatedCost) {
		var ret string
		return ret
	}
	return *o.EstimatedCost
}

// GetEstimatedCostOk returns a tuple with the EstimatedCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetEstimatedCostOk() (*string, bool) {
	if o == nil || IsNil(o.EstimatedCost) {
		return nil, false
	}
	return o.EstimatedCost, true
}

// HasEstimatedCost returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasEstimatedCost() bool {
	if o != nil && !IsNil(o.EstimatedCost) {
		return true
	}

	return false
}

// SetEstimatedCost gets a reference to the given string and assigns it to the EstimatedCost field.
func (o *CalculateWalletFee200ResponseData) SetEstimatedCost(v string) {
	o.EstimatedCost = &v
}

// GetSatPerVb returns the SatPerVb field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetSatPerVb() int32 {
	if o == nil || IsNil(o.SatPerVb) {
		var ret int32
		return ret
	}
	return *o.SatPerVb
}

// GetSatPerVbOk returns a tuple with the SatPerVb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetSatPerVbOk() (*int32, bool) {
	if o == nil || IsNil(o.SatPerVb) {
		return nil, false
	}
	return o.SatPerVb, true
}

// HasSatPerVb returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasSatPerVb() bool {
	if o != nil && !IsNil(o.SatPerVb) {
		return true
	}

	return false
}

// SetSatPerVb gets a reference to the given int32 and assigns it to the SatPerVb field.
func (o *CalculateWalletFee200ResponseData) SetSatPerVb(v int32) {
	o.SatPerVb = &v
}

// GetFeeSat returns the FeeSat field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetFeeSat() int32 {
	if o == nil || IsNil(o.FeeSat) {
		var ret int32
		return ret
	}
	return *o.FeeSat
}

// GetFeeSatOk returns a tuple with the FeeSat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetFeeSatOk() (*int32, bool) {
	if o == nil || IsNil(o.FeeSat) {
		return nil, false
	}
	return o.FeeSat, true
}

// HasFeeSat returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasFeeSat() bool {
	if o != nil && !IsNil(o.FeeSat) {
		return true
	}

	return false
}

// SetFeeSat gets a reference to the given int32 and assigns it to the FeeSat field.
func (o *CalculateWalletFee200ResponseData) SetFeeSat(v int32) {
	o.FeeSat = &v
}

// GetLamports returns the Lamports field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetLamports() int32 {
	if o == nil || IsNil(o.Lamports) {
		var ret int32
		return ret
	}
	return *o.Lamports
}

// GetLamportsOk returns a tuple with the Lamports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetLamportsOk() (*int32, bool) {
	if o == nil || IsNil(o.Lamports) {
		return nil, false
	}
	return o.Lamports, true
}

// HasLamports returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasLamports() bool {
	if o != nil && !IsNil(o.Lamports) {
		return true
	}

	return false
}

// SetLamports gets a reference to the given int32 and assigns it to the Lamports field.
func (o *CalculateWalletFee200ResponseData) SetLamports(v int32) {
	o.Lamports = &v
}

// GetFeeTiers returns the FeeTiers field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetFeeTiers() map[string]CalculateWalletFee200ResponseDataFeeTiersValue {
	if o == nil || IsNil(o.FeeTiers) {
		var ret map[string]CalculateWalletFee200ResponseDataFeeTiersValue
		return ret
	}
	return *o.FeeTiers
}

// GetFeeTiersOk returns a tuple with the FeeTiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetFeeTiersOk() (*map[string]CalculateWalletFee200ResponseDataFeeTiersValue, bool) {
	if o == nil || IsNil(o.FeeTiers) {
		return nil, false
	}
	return o.FeeTiers, true
}

// HasFeeTiers returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasFeeTiers() bool {
	if o != nil && !IsNil(o.FeeTiers) {
		return true
	}

	return false
}

// SetFeeTiers gets a reference to the given map[string]CalculateWalletFee200ResponseDataFeeTiersValue and assigns it to the FeeTiers field.
func (o *CalculateWalletFee200ResponseData) SetFeeTiers(v map[string]CalculateWalletFee200ResponseDataFeeTiersValue) {
	o.FeeTiers = &v
}

// GetGasSpikeWarning returns the GasSpikeWarning field value if set, zero value otherwise.
func (o *CalculateWalletFee200ResponseData) GetGasSpikeWarning() bool {
	if o == nil || IsNil(o.GasSpikeWarning) {
		var ret bool
		return ret
	}
	return *o.GasSpikeWarning
}

// GetGasSpikeWarningOk returns a tuple with the GasSpikeWarning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateWalletFee200ResponseData) GetGasSpikeWarningOk() (*bool, bool) {
	if o == nil || IsNil(o.GasSpikeWarning) {
		return nil, false
	}
	return o.GasSpikeWarning, true
}

// HasGasSpikeWarning returns a boolean if a field has been set.
func (o *CalculateWalletFee200ResponseData) HasGasSpikeWarning() bool {
	if o != nil && !IsNil(o.GasSpikeWarning) {
		return true
	}

	return false
}

// SetGasSpikeWarning gets a reference to the given bool and assigns it to the GasSpikeWarning field.
func (o *CalculateWalletFee200ResponseData) SetGasSpikeWarning(v bool) {
	o.GasSpikeWarning = &v
}

func (o CalculateWalletFee200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalculateWalletFee200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if o.Network.IsSet() {
		toSerialize["network"] = o.Network.Get()
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Chain) {
		toSerialize["chain"] = o.Chain
	}
	if !IsNil(o.NetworkFee) {
		toSerialize["networkFee"] = o.NetworkFee
	}
	if !IsNil(o.EstimatedTime) {
		toSerialize["estimatedTime"] = o.EstimatedTime
	}
	if !IsNil(o.Congestion) {
		toSerialize["congestion"] = o.Congestion
	}
	if !IsNil(o.GasLimit) {
		toSerialize["gasLimit"] = o.GasLimit
	}
	if !IsNil(o.GasPrice) {
		toSerialize["gasPrice"] = o.GasPrice
	}
	if !IsNil(o.GasPriceGwei) {
		toSerialize["gasPriceGwei"] = o.GasPriceGwei
	}
	if !IsNil(o.EstimatedCost) {
		toSerialize["estimatedCost"] = o.EstimatedCost
	}
	if !IsNil(o.SatPerVb) {
		toSerialize["satPerVb"] = o.SatPerVb
	}
	if !IsNil(o.FeeSat) {
		toSerialize["feeSat"] = o.FeeSat
	}
	if !IsNil(o.Lamports) {
		toSerialize["lamports"] = o.Lamports
	}
	if !IsNil(o.FeeTiers) {
		toSerialize["feeTiers"] = o.FeeTiers
	}
	if !IsNil(o.GasSpikeWarning) {
		toSerialize["gasSpikeWarning"] = o.GasSpikeWarning
	}
	return toSerialize, nil
}

type NullableCalculateWalletFee200ResponseData struct {
	value *CalculateWalletFee200ResponseData
	isSet bool
}

func (v NullableCalculateWalletFee200ResponseData) Get() *CalculateWalletFee200ResponseData {
	return v.value
}

func (v *NullableCalculateWalletFee200ResponseData) Set(val *CalculateWalletFee200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCalculateWalletFee200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCalculateWalletFee200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalculateWalletFee200ResponseData(val *CalculateWalletFee200ResponseData) *NullableCalculateWalletFee200ResponseData {
	return &NullableCalculateWalletFee200ResponseData{value: val, isSet: true}
}

func (v NullableCalculateWalletFee200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalculateWalletFee200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


