/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.7
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the ExecuteFunctionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecuteFunctionRequest{}

// ExecuteFunctionRequest struct for ExecuteFunctionRequest
type ExecuteFunctionRequest struct {
	// Custom input merged with trigger context
	Payload map[string]interface{} `json:"payload,omitempty"`
}

// NewExecuteFunctionRequest instantiates a new ExecuteFunctionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecuteFunctionRequest() *ExecuteFunctionRequest {
	this := ExecuteFunctionRequest{}
	return &this
}

// NewExecuteFunctionRequestWithDefaults instantiates a new ExecuteFunctionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecuteFunctionRequestWithDefaults() *ExecuteFunctionRequest {
	this := ExecuteFunctionRequest{}
	return &this
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *ExecuteFunctionRequest) GetPayload() map[string]interface{} {
	if o == nil || IsNil(o.Payload) {
		var ret map[string]interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExecuteFunctionRequest) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *ExecuteFunctionRequest) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given map[string]interface{} and assigns it to the Payload field.
func (o *ExecuteFunctionRequest) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

func (o ExecuteFunctionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecuteFunctionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	return toSerialize, nil
}

type NullableExecuteFunctionRequest struct {
	value *ExecuteFunctionRequest
	isSet bool
}

func (v NullableExecuteFunctionRequest) Get() *ExecuteFunctionRequest {
	return v.value
}

func (v *NullableExecuteFunctionRequest) Set(val *ExecuteFunctionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExecuteFunctionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExecuteFunctionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecuteFunctionRequest(val *ExecuteFunctionRequest) *NullableExecuteFunctionRequest {
	return &NullableExecuteFunctionRequest{value: val, isSet: true}
}

func (v NullableExecuteFunctionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecuteFunctionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


