/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.5
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrgDnsInstructionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrgDnsInstructionsResponse{}

// OrgDnsInstructionsResponse struct for OrgDnsInstructionsResponse
type OrgDnsInstructionsResponse struct {
	Success bool `json:"success"`
	Domain OrgDomainEntryOrgConsole `json:"domain"`
	// Plain-language reminder to add the ownership TXT from the domain’s DNS checklist, then use Verify DNS in the organization’s domain settings.
	DnsVerificationInstructions *string `json:"dnsVerificationInstructions,omitempty"`
}

type _OrgDnsInstructionsResponse OrgDnsInstructionsResponse

// NewOrgDnsInstructionsResponse instantiates a new OrgDnsInstructionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrgDnsInstructionsResponse(success bool, domain OrgDomainEntryOrgConsole) *OrgDnsInstructionsResponse {
	this := OrgDnsInstructionsResponse{}
	this.Success = success
	this.Domain = domain
	return &this
}

// NewOrgDnsInstructionsResponseWithDefaults instantiates a new OrgDnsInstructionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrgDnsInstructionsResponseWithDefaults() *OrgDnsInstructionsResponse {
	this := OrgDnsInstructionsResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *OrgDnsInstructionsResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *OrgDnsInstructionsResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *OrgDnsInstructionsResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetDomain returns the Domain field value
func (o *OrgDnsInstructionsResponse) GetDomain() OrgDomainEntryOrgConsole {
	if o == nil {
		var ret OrgDomainEntryOrgConsole
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *OrgDnsInstructionsResponse) GetDomainOk() (*OrgDomainEntryOrgConsole, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *OrgDnsInstructionsResponse) SetDomain(v OrgDomainEntryOrgConsole) {
	o.Domain = v
}

// GetDnsVerificationInstructions returns the DnsVerificationInstructions field value if set, zero value otherwise.
func (o *OrgDnsInstructionsResponse) GetDnsVerificationInstructions() string {
	if o == nil || IsNil(o.DnsVerificationInstructions) {
		var ret string
		return ret
	}
	return *o.DnsVerificationInstructions
}

// GetDnsVerificationInstructionsOk returns a tuple with the DnsVerificationInstructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgDnsInstructionsResponse) GetDnsVerificationInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.DnsVerificationInstructions) {
		return nil, false
	}
	return o.DnsVerificationInstructions, true
}

// HasDnsVerificationInstructions returns a boolean if a field has been set.
func (o *OrgDnsInstructionsResponse) HasDnsVerificationInstructions() bool {
	if o != nil && !IsNil(o.DnsVerificationInstructions) {
		return true
	}

	return false
}

// SetDnsVerificationInstructions gets a reference to the given string and assigns it to the DnsVerificationInstructions field.
func (o *OrgDnsInstructionsResponse) SetDnsVerificationInstructions(v string) {
	o.DnsVerificationInstructions = &v
}

func (o OrgDnsInstructionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrgDnsInstructionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["domain"] = o.Domain
	if !IsNil(o.DnsVerificationInstructions) {
		toSerialize["dnsVerificationInstructions"] = o.DnsVerificationInstructions
	}
	return toSerialize, nil
}

func (o *OrgDnsInstructionsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"domain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrgDnsInstructionsResponse := _OrgDnsInstructionsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrgDnsInstructionsResponse)

	if err != nil {
		return err
	}

	*o = OrgDnsInstructionsResponse(varOrgDnsInstructionsResponse)

	return err
}

type NullableOrgDnsInstructionsResponse struct {
	value *OrgDnsInstructionsResponse
	isSet bool
}

func (v NullableOrgDnsInstructionsResponse) Get() *OrgDnsInstructionsResponse {
	return v.value
}

func (v *NullableOrgDnsInstructionsResponse) Set(val *OrgDnsInstructionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgDnsInstructionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgDnsInstructionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgDnsInstructionsResponse(val *OrgDnsInstructionsResponse) *NullableOrgDnsInstructionsResponse {
	return &NullableOrgDnsInstructionsResponse{value: val, isSet: true}
}

func (v NullableOrgDnsInstructionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgDnsInstructionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


