/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.8
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the GetWebhookConfig200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWebhookConfig200Response{}

// GetWebhookConfig200Response struct for GetWebhookConfig200Response
type GetWebhookConfig200Response struct {
	Success *bool `json:"success,omitempty"`
	Data *GetWebhookConfig200ResponseData `json:"data,omitempty"`
}

// NewGetWebhookConfig200Response instantiates a new GetWebhookConfig200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWebhookConfig200Response() *GetWebhookConfig200Response {
	this := GetWebhookConfig200Response{}
	return &this
}

// NewGetWebhookConfig200ResponseWithDefaults instantiates a new GetWebhookConfig200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWebhookConfig200ResponseWithDefaults() *GetWebhookConfig200Response {
	this := GetWebhookConfig200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetWebhookConfig200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebhookConfig200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetWebhookConfig200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetWebhookConfig200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetWebhookConfig200Response) GetData() GetWebhookConfig200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret GetWebhookConfig200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebhookConfig200Response) GetDataOk() (*GetWebhookConfig200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetWebhookConfig200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GetWebhookConfig200ResponseData and assigns it to the Data field.
func (o *GetWebhookConfig200Response) SetData(v GetWebhookConfig200ResponseData) {
	o.Data = &v
}

func (o GetWebhookConfig200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWebhookConfig200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetWebhookConfig200Response struct {
	value *GetWebhookConfig200Response
	isSet bool
}

func (v NullableGetWebhookConfig200Response) Get() *GetWebhookConfig200Response {
	return v.value
}

func (v *NullableGetWebhookConfig200Response) Set(val *GetWebhookConfig200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWebhookConfig200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWebhookConfig200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWebhookConfig200Response(val *GetWebhookConfig200Response) *NullableGetWebhookConfig200Response {
	return &NullableGetWebhookConfig200Response{value: val, isSet: true}
}

func (v NullableGetWebhookConfig200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWebhookConfig200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


