/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.3
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the InviteTeamMember200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteTeamMember200Response{}

// InviteTeamMember200Response struct for InviteTeamMember200Response
type InviteTeamMember200Response struct {
	Message *string `json:"message,omitempty"`
	Email *string `json:"email,omitempty"`
	Role *string `json:"role,omitempty"`
}

// NewInviteTeamMember200Response instantiates a new InviteTeamMember200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteTeamMember200Response() *InviteTeamMember200Response {
	this := InviteTeamMember200Response{}
	return &this
}

// NewInviteTeamMember200ResponseWithDefaults instantiates a new InviteTeamMember200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteTeamMember200ResponseWithDefaults() *InviteTeamMember200Response {
	this := InviteTeamMember200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *InviteTeamMember200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteTeamMember200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *InviteTeamMember200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *InviteTeamMember200Response) SetMessage(v string) {
	o.Message = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *InviteTeamMember200Response) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteTeamMember200Response) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *InviteTeamMember200Response) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *InviteTeamMember200Response) SetEmail(v string) {
	o.Email = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *InviteTeamMember200Response) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteTeamMember200Response) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *InviteTeamMember200Response) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *InviteTeamMember200Response) SetRole(v string) {
	o.Role = &v
}

func (o InviteTeamMember200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteTeamMember200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

type NullableInviteTeamMember200Response struct {
	value *InviteTeamMember200Response
	isSet bool
}

func (v NullableInviteTeamMember200Response) Get() *InviteTeamMember200Response {
	return v.value
}

func (v *NullableInviteTeamMember200Response) Set(val *InviteTeamMember200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteTeamMember200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteTeamMember200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteTeamMember200Response(val *InviteTeamMember200Response) *NullableInviteTeamMember200Response {
	return &NullableInviteTeamMember200Response{value: val, isSet: true}
}

func (v NullableInviteTeamMember200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteTeamMember200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


