/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.5
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the ConfigureWebhook200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigureWebhook200ResponseData{}

// ConfigureWebhook200ResponseData struct for ConfigureWebhook200ResponseData
type ConfigureWebhook200ResponseData struct {
	WebhookUrl NullableString `json:"webhookUrl,omitempty"`
	WebhookEvents []string `json:"webhookEvents,omitempty"`
	WebhookVersion *string `json:"webhookVersion,omitempty"`
	Transformations []ConfigureWebhook200ResponseDataTransformationsInner `json:"transformations,omitempty"`
}

// NewConfigureWebhook200ResponseData instantiates a new ConfigureWebhook200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigureWebhook200ResponseData() *ConfigureWebhook200ResponseData {
	this := ConfigureWebhook200ResponseData{}
	return &this
}

// NewConfigureWebhook200ResponseDataWithDefaults instantiates a new ConfigureWebhook200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigureWebhook200ResponseDataWithDefaults() *ConfigureWebhook200ResponseData {
	this := ConfigureWebhook200ResponseData{}
	return &this
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigureWebhook200ResponseData) GetWebhookUrl() string {
	if o == nil || IsNil(o.WebhookUrl.Get()) {
		var ret string
		return ret
	}
	return *o.WebhookUrl.Get()
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigureWebhook200ResponseData) GetWebhookUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookUrl.Get(), o.WebhookUrl.IsSet()
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *ConfigureWebhook200ResponseData) HasWebhookUrl() bool {
	if o != nil && o.WebhookUrl.IsSet() {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given NullableString and assigns it to the WebhookUrl field.
func (o *ConfigureWebhook200ResponseData) SetWebhookUrl(v string) {
	o.WebhookUrl.Set(&v)
}
// SetWebhookUrlNil sets the value for WebhookUrl to be an explicit nil
func (o *ConfigureWebhook200ResponseData) SetWebhookUrlNil() {
	o.WebhookUrl.Set(nil)
}

// UnsetWebhookUrl ensures that no value is present for WebhookUrl, not even an explicit nil
func (o *ConfigureWebhook200ResponseData) UnsetWebhookUrl() {
	o.WebhookUrl.Unset()
}

// GetWebhookEvents returns the WebhookEvents field value if set, zero value otherwise.
func (o *ConfigureWebhook200ResponseData) GetWebhookEvents() []string {
	if o == nil || IsNil(o.WebhookEvents) {
		var ret []string
		return ret
	}
	return o.WebhookEvents
}

// GetWebhookEventsOk returns a tuple with the WebhookEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureWebhook200ResponseData) GetWebhookEventsOk() ([]string, bool) {
	if o == nil || IsNil(o.WebhookEvents) {
		return nil, false
	}
	return o.WebhookEvents, true
}

// HasWebhookEvents returns a boolean if a field has been set.
func (o *ConfigureWebhook200ResponseData) HasWebhookEvents() bool {
	if o != nil && !IsNil(o.WebhookEvents) {
		return true
	}

	return false
}

// SetWebhookEvents gets a reference to the given []string and assigns it to the WebhookEvents field.
func (o *ConfigureWebhook200ResponseData) SetWebhookEvents(v []string) {
	o.WebhookEvents = v
}

// GetWebhookVersion returns the WebhookVersion field value if set, zero value otherwise.
func (o *ConfigureWebhook200ResponseData) GetWebhookVersion() string {
	if o == nil || IsNil(o.WebhookVersion) {
		var ret string
		return ret
	}
	return *o.WebhookVersion
}

// GetWebhookVersionOk returns a tuple with the WebhookVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureWebhook200ResponseData) GetWebhookVersionOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookVersion) {
		return nil, false
	}
	return o.WebhookVersion, true
}

// HasWebhookVersion returns a boolean if a field has been set.
func (o *ConfigureWebhook200ResponseData) HasWebhookVersion() bool {
	if o != nil && !IsNil(o.WebhookVersion) {
		return true
	}

	return false
}

// SetWebhookVersion gets a reference to the given string and assigns it to the WebhookVersion field.
func (o *ConfigureWebhook200ResponseData) SetWebhookVersion(v string) {
	o.WebhookVersion = &v
}

// GetTransformations returns the Transformations field value if set, zero value otherwise.
func (o *ConfigureWebhook200ResponseData) GetTransformations() []ConfigureWebhook200ResponseDataTransformationsInner {
	if o == nil || IsNil(o.Transformations) {
		var ret []ConfigureWebhook200ResponseDataTransformationsInner
		return ret
	}
	return o.Transformations
}

// GetTransformationsOk returns a tuple with the Transformations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureWebhook200ResponseData) GetTransformationsOk() ([]ConfigureWebhook200ResponseDataTransformationsInner, bool) {
	if o == nil || IsNil(o.Transformations) {
		return nil, false
	}
	return o.Transformations, true
}

// HasTransformations returns a boolean if a field has been set.
func (o *ConfigureWebhook200ResponseData) HasTransformations() bool {
	if o != nil && !IsNil(o.Transformations) {
		return true
	}

	return false
}

// SetTransformations gets a reference to the given []ConfigureWebhook200ResponseDataTransformationsInner and assigns it to the Transformations field.
func (o *ConfigureWebhook200ResponseData) SetTransformations(v []ConfigureWebhook200ResponseDataTransformationsInner) {
	o.Transformations = v
}

func (o ConfigureWebhook200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigureWebhook200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.WebhookUrl.IsSet() {
		toSerialize["webhookUrl"] = o.WebhookUrl.Get()
	}
	if !IsNil(o.WebhookEvents) {
		toSerialize["webhookEvents"] = o.WebhookEvents
	}
	if !IsNil(o.WebhookVersion) {
		toSerialize["webhookVersion"] = o.WebhookVersion
	}
	if !IsNil(o.Transformations) {
		toSerialize["transformations"] = o.Transformations
	}
	return toSerialize, nil
}

type NullableConfigureWebhook200ResponseData struct {
	value *ConfigureWebhook200ResponseData
	isSet bool
}

func (v NullableConfigureWebhook200ResponseData) Get() *ConfigureWebhook200ResponseData {
	return v.value
}

func (v *NullableConfigureWebhook200ResponseData) Set(val *ConfigureWebhook200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigureWebhook200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigureWebhook200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigureWebhook200ResponseData(val *ConfigureWebhook200ResponseData) *NullableConfigureWebhook200ResponseData {
	return &NullableConfigureWebhook200ResponseData{value: val, isSet: true}
}

func (v NullableConfigureWebhook200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigureWebhook200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


