/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.9
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the BillingCreateCheckoutSession200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingCreateCheckoutSession200ResponseData{}

// BillingCreateCheckoutSession200ResponseData struct for BillingCreateCheckoutSession200ResponseData
type BillingCreateCheckoutSession200ResponseData struct {
	// Checkout/page URL (crypto) or null when Flutterwave
	CheckoutUrl *string `json:"checkoutUrl,omitempty"`
	// Flutterwave redirect URL (when Flutterwave is used)
	AuthorizationUrl *string `json:"authorizationUrl,omitempty"`
	// Flutterwave access code
	AccessCode *string `json:"accessCode,omitempty"`
	// Payment reference (e.g. mudbase_xxx or pmt_xxx)
	Reference *string `json:"reference,omitempty"`
	// Payment intent ID (crypto)
	PaymentId *string `json:"paymentId,omitempty"`
	// Multi-chain payment options (crypto)
	PaymentOptions []BillingCreateCheckoutSession200ResponseDataPaymentOptionsInner `json:"paymentOptions,omitempty"`
	PaymentAddress *string `json:"paymentAddress,omitempty"`
	Network *string `json:"network,omitempty"`
	Asset *string `json:"asset,omitempty"`
	Amount *float32 `json:"amount,omitempty"`
	Currency *string `json:"currency,omitempty"`
}

// NewBillingCreateCheckoutSession200ResponseData instantiates a new BillingCreateCheckoutSession200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingCreateCheckoutSession200ResponseData() *BillingCreateCheckoutSession200ResponseData {
	this := BillingCreateCheckoutSession200ResponseData{}
	return &this
}

// NewBillingCreateCheckoutSession200ResponseDataWithDefaults instantiates a new BillingCreateCheckoutSession200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingCreateCheckoutSession200ResponseDataWithDefaults() *BillingCreateCheckoutSession200ResponseData {
	this := BillingCreateCheckoutSession200ResponseData{}
	return &this
}

// GetCheckoutUrl returns the CheckoutUrl field value if set, zero value otherwise.
func (o *BillingCreateCheckoutSession200ResponseData) GetCheckoutUrl() string {
	if o == nil || IsNil(o.CheckoutUrl) {
		var ret string
		return ret
	}
	return *o.CheckoutUrl
}

// GetCheckoutUrlOk returns a tuple with the CheckoutUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingCreateCheckoutSession200ResponseData) GetCheckoutUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CheckoutUrl) {
		return nil, false
	}
	return o.CheckoutUrl, true
}

// HasCheckoutUrl returns a boolean if a field has been set.
func (o *BillingCreateCheckoutSession200ResponseData) HasCheckoutUrl() bool {
	if o != nil && !IsNil(o.CheckoutUrl) {
		return true
	}

	return false
}

// SetCheckoutUrl gets a reference to the given string and assigns it to the CheckoutUrl field.
func (o *BillingCreateCheckoutSession200ResponseData) SetCheckoutUrl(v string) {
	o.CheckoutUrl = &v
}

// GetAuthorizationUrl returns the AuthorizationUrl field value if set, zero value otherwise.
func (o *BillingCreateCheckoutSession200ResponseData) GetAuthorizationUrl() string {
	if o == nil || IsNil(o.AuthorizationUrl) {
		var ret string
		return ret
	}
	return *o.AuthorizationUrl
}

// GetAuthorizationUrlOk returns a tuple with the AuthorizationUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingCreateCheckoutSession200ResponseData) GetAuthorizationUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorizationUrl) {
		return nil, false
	}
	return o.AuthorizationUrl, true
}

// HasAuthorizationUrl returns a boolean if a field has been set.
func (o *BillingCreateCheckoutSession200ResponseData) HasAuthorizationUrl() bool {
	if o != nil && !IsNil(o.AuthorizationUrl) {
		return true
	}

	return false
}

// SetAuthorizationUrl gets a reference to the given string and assigns it to the AuthorizationUrl field.
func (o *BillingCreateCheckoutSession200ResponseData) SetAuthorizationUrl(v string) {
	o.AuthorizationUrl = &v
}

// GetAccessCode returns the AccessCode field value if set, zero value otherwise.
func (o *BillingCreateCheckoutSession200ResponseData) GetAccessCode() string {
	if o == nil || IsNil(o.AccessCode) {
		var ret string
		return ret
	}
	return *o.AccessCode
}

// GetAccessCodeOk returns a tuple with the AccessCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingCreateCheckoutSession200ResponseData) GetAccessCodeOk() (*string, bool) {
	if o == nil || IsNil(o.AccessCode) {
		return nil, false
	}
	return o.AccessCode, true
}

// HasAccessCode returns a boolean if a field has been set.
func (o *BillingCreateCheckoutSession200ResponseData) HasAccessCode() bool {
	if o != nil && !IsNil(o.AccessCode) {
		return true
	}

	return false
}

// SetAccessCode gets a reference to the given string and assigns it to the AccessCode field.
func (o *BillingCreateCheckoutSession200ResponseData) SetAccessCode(v string) {
	o.AccessCode = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *BillingCreateCheckoutSession200ResponseData) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingCreateCheckoutSession200ResponseData) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *BillingCreateCheckoutSession200ResponseData) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *BillingCreateCheckoutSession200ResponseData) SetReference(v string) {
	o.Reference = &v
}

// GetPaymentId returns the PaymentId field value if set, zero value otherwise.
func (o *BillingCreateCheckoutSession200ResponseData) GetPaymentId() string {
	if o == nil || IsNil(o.PaymentId) {
		var ret string
		return ret
	}
	return *o.PaymentId
}

// GetPaymentIdOk returns a tuple with the PaymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingCreateCheckoutSession200ResponseData) GetPaymentIdOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentId) {
		return nil, false
	}
	return o.PaymentId, true
}

// HasPaymentId returns a boolean if a field has been set.
func (o *BillingCreateCheckoutSession200ResponseData) HasPaymentId() bool {
	if o != nil && !IsNil(o.PaymentId) {
		return true
	}

	return false
}

// SetPaymentId gets a reference to the given string and assigns it to the PaymentId field.
func (o *BillingCreateCheckoutSession200ResponseData) SetPaymentId(v string) {
	o.PaymentId = &v
}

// GetPaymentOptions returns the PaymentOptions field value if set, zero value otherwise.
func (o *BillingCreateCheckoutSession200ResponseData) GetPaymentOptions() []BillingCreateCheckoutSession200ResponseDataPaymentOptionsInner {
	if o == nil || IsNil(o.PaymentOptions) {
		var ret []BillingCreateCheckoutSession200ResponseDataPaymentOptionsInner
		return ret
	}
	return o.PaymentOptions
}

// GetPaymentOptionsOk returns a tuple with the PaymentOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingCreateCheckoutSession200ResponseData) GetPaymentOptionsOk() ([]BillingCreateCheckoutSession200ResponseDataPaymentOptionsInner, bool) {
	if o == nil || IsNil(o.PaymentOptions) {
		return nil, false
	}
	return o.PaymentOptions, true
}

// HasPaymentOptions returns a boolean if a field has been set.
func (o *BillingCreateCheckoutSession200ResponseData) HasPaymentOptions() bool {
	if o != nil && !IsNil(o.PaymentOptions) {
		return true
	}

	return false
}

// SetPaymentOptions gets a reference to the given []BillingCreateCheckoutSession200ResponseDataPaymentOptionsInner and assigns it to the PaymentOptions field.
func (o *BillingCreateCheckoutSession200ResponseData) SetPaymentOptions(v []BillingCreateCheckoutSession200ResponseDataPaymentOptionsInner) {
	o.PaymentOptions = v
}

// GetPaymentAddress returns the PaymentAddress field value if set, zero value otherwise.
func (o *BillingCreateCheckoutSession200ResponseData) GetPaymentAddress() string {
	if o == nil || IsNil(o.PaymentAddress) {
		var ret string
		return ret
	}
	return *o.PaymentAddress
}

// GetPaymentAddressOk returns a tuple with the PaymentAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingCreateCheckoutSession200ResponseData) GetPaymentAddressOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentAddress) {
		return nil, false
	}
	return o.PaymentAddress, true
}

// HasPaymentAddress returns a boolean if a field has been set.
func (o *BillingCreateCheckoutSession200ResponseData) HasPaymentAddress() bool {
	if o != nil && !IsNil(o.PaymentAddress) {
		return true
	}

	return false
}

// SetPaymentAddress gets a reference to the given string and assigns it to the PaymentAddress field.
func (o *BillingCreateCheckoutSession200ResponseData) SetPaymentAddress(v string) {
	o.PaymentAddress = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *BillingCreateCheckoutSession200ResponseData) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingCreateCheckoutSession200ResponseData) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *BillingCreateCheckoutSession200ResponseData) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *BillingCreateCheckoutSession200ResponseData) SetNetwork(v string) {
	o.Network = &v
}

// GetAsset returns the Asset field value if set, zero value otherwise.
func (o *BillingCreateCheckoutSession200ResponseData) GetAsset() string {
	if o == nil || IsNil(o.Asset) {
		var ret string
		return ret
	}
	return *o.Asset
}

// GetAssetOk returns a tuple with the Asset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingCreateCheckoutSession200ResponseData) GetAssetOk() (*string, bool) {
	if o == nil || IsNil(o.Asset) {
		return nil, false
	}
	return o.Asset, true
}

// HasAsset returns a boolean if a field has been set.
func (o *BillingCreateCheckoutSession200ResponseData) HasAsset() bool {
	if o != nil && !IsNil(o.Asset) {
		return true
	}

	return false
}

// SetAsset gets a reference to the given string and assigns it to the Asset field.
func (o *BillingCreateCheckoutSession200ResponseData) SetAsset(v string) {
	o.Asset = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *BillingCreateCheckoutSession200ResponseData) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingCreateCheckoutSession200ResponseData) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *BillingCreateCheckoutSession200ResponseData) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *BillingCreateCheckoutSession200ResponseData) SetAmount(v float32) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *BillingCreateCheckoutSession200ResponseData) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingCreateCheckoutSession200ResponseData) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *BillingCreateCheckoutSession200ResponseData) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *BillingCreateCheckoutSession200ResponseData) SetCurrency(v string) {
	o.Currency = &v
}

func (o BillingCreateCheckoutSession200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingCreateCheckoutSession200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CheckoutUrl) {
		toSerialize["checkoutUrl"] = o.CheckoutUrl
	}
	if !IsNil(o.AuthorizationUrl) {
		toSerialize["authorizationUrl"] = o.AuthorizationUrl
	}
	if !IsNil(o.AccessCode) {
		toSerialize["accessCode"] = o.AccessCode
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	if !IsNil(o.PaymentId) {
		toSerialize["paymentId"] = o.PaymentId
	}
	if !IsNil(o.PaymentOptions) {
		toSerialize["paymentOptions"] = o.PaymentOptions
	}
	if !IsNil(o.PaymentAddress) {
		toSerialize["paymentAddress"] = o.PaymentAddress
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.Asset) {
		toSerialize["asset"] = o.Asset
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	return toSerialize, nil
}

type NullableBillingCreateCheckoutSession200ResponseData struct {
	value *BillingCreateCheckoutSession200ResponseData
	isSet bool
}

func (v NullableBillingCreateCheckoutSession200ResponseData) Get() *BillingCreateCheckoutSession200ResponseData {
	return v.value
}

func (v *NullableBillingCreateCheckoutSession200ResponseData) Set(val *BillingCreateCheckoutSession200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingCreateCheckoutSession200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingCreateCheckoutSession200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingCreateCheckoutSession200ResponseData(val *BillingCreateCheckoutSession200ResponseData) *NullableBillingCreateCheckoutSession200ResponseData {
	return &NullableBillingCreateCheckoutSession200ResponseData{value: val, isSet: true}
}

func (v NullableBillingCreateCheckoutSession200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingCreateCheckoutSession200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


