/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave for fiat (platform subscriptions and payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.12
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the MessageSentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageSentResponse{}

// MessageSentResponse Response after sending a message (success, data with id, type, status, recipients, sentAt).
type MessageSentResponse struct {
	Success *bool `json:"success,omitempty"`
	Data *MessageSentResponseData `json:"data,omitempty"`
}

// NewMessageSentResponse instantiates a new MessageSentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageSentResponse() *MessageSentResponse {
	this := MessageSentResponse{}
	return &this
}

// NewMessageSentResponseWithDefaults instantiates a new MessageSentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageSentResponseWithDefaults() *MessageSentResponse {
	this := MessageSentResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *MessageSentResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSentResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *MessageSentResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *MessageSentResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *MessageSentResponse) GetData() MessageSentResponseData {
	if o == nil || IsNil(o.Data) {
		var ret MessageSentResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageSentResponse) GetDataOk() (*MessageSentResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *MessageSentResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given MessageSentResponseData and assigns it to the Data field.
func (o *MessageSentResponse) SetData(v MessageSentResponseData) {
	o.Data = &v
}

func (o MessageSentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageSentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableMessageSentResponse struct {
	value *MessageSentResponse
	isSet bool
}

func (v NullableMessageSentResponse) Get() *MessageSentResponse {
	return v.value
}

func (v *NullableMessageSentResponse) Set(val *MessageSentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageSentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageSentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageSentResponse(val *MessageSentResponse) *NullableMessageSentResponse {
	return &NullableMessageSentResponse{value: val, isSet: true}
}

func (v NullableMessageSentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageSentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


