/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.5
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the BillingCheckFeatureAccess200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingCheckFeatureAccess200Response{}

// BillingCheckFeatureAccess200Response struct for BillingCheckFeatureAccess200Response
type BillingCheckFeatureAccess200Response struct {
	HasAccess *bool `json:"hasAccess,omitempty"`
	Reason *string `json:"reason,omitempty"`
}

// NewBillingCheckFeatureAccess200Response instantiates a new BillingCheckFeatureAccess200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingCheckFeatureAccess200Response() *BillingCheckFeatureAccess200Response {
	this := BillingCheckFeatureAccess200Response{}
	return &this
}

// NewBillingCheckFeatureAccess200ResponseWithDefaults instantiates a new BillingCheckFeatureAccess200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingCheckFeatureAccess200ResponseWithDefaults() *BillingCheckFeatureAccess200Response {
	this := BillingCheckFeatureAccess200Response{}
	return &this
}

// GetHasAccess returns the HasAccess field value if set, zero value otherwise.
func (o *BillingCheckFeatureAccess200Response) GetHasAccess() bool {
	if o == nil || IsNil(o.HasAccess) {
		var ret bool
		return ret
	}
	return *o.HasAccess
}

// GetHasAccessOk returns a tuple with the HasAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingCheckFeatureAccess200Response) GetHasAccessOk() (*bool, bool) {
	if o == nil || IsNil(o.HasAccess) {
		return nil, false
	}
	return o.HasAccess, true
}

// HasHasAccess returns a boolean if a field has been set.
func (o *BillingCheckFeatureAccess200Response) HasHasAccess() bool {
	if o != nil && !IsNil(o.HasAccess) {
		return true
	}

	return false
}

// SetHasAccess gets a reference to the given bool and assigns it to the HasAccess field.
func (o *BillingCheckFeatureAccess200Response) SetHasAccess(v bool) {
	o.HasAccess = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *BillingCheckFeatureAccess200Response) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingCheckFeatureAccess200Response) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *BillingCheckFeatureAccess200Response) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *BillingCheckFeatureAccess200Response) SetReason(v string) {
	o.Reason = &v
}

func (o BillingCheckFeatureAccess200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingCheckFeatureAccess200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HasAccess) {
		toSerialize["hasAccess"] = o.HasAccess
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

type NullableBillingCheckFeatureAccess200Response struct {
	value *BillingCheckFeatureAccess200Response
	isSet bool
}

func (v NullableBillingCheckFeatureAccess200Response) Get() *BillingCheckFeatureAccess200Response {
	return v.value
}

func (v *NullableBillingCheckFeatureAccess200Response) Set(val *BillingCheckFeatureAccess200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingCheckFeatureAccess200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingCheckFeatureAccess200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingCheckFeatureAccess200Response(val *BillingCheckFeatureAccess200Response) *NullableBillingCheckFeatureAccess200Response {
	return &NullableBillingCheckFeatureAccess200Response{value: val, isSet: true}
}

func (v NullableBillingCheckFeatureAccess200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingCheckFeatureAccess200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


