/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.5
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the CollectionPermissionRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollectionPermissionRule{}

// CollectionPermissionRule Explicit actions + row-level conditions granted on a collection
type CollectionPermissionRule struct {
	Actions []CollectionAction `json:"actions,omitempty"`
	Conditions map[string]interface{} `json:"conditions,omitempty"`
}

// NewCollectionPermissionRule instantiates a new CollectionPermissionRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionPermissionRule() *CollectionPermissionRule {
	this := CollectionPermissionRule{}
	return &this
}

// NewCollectionPermissionRuleWithDefaults instantiates a new CollectionPermissionRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionPermissionRuleWithDefaults() *CollectionPermissionRule {
	this := CollectionPermissionRule{}
	return &this
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *CollectionPermissionRule) GetActions() []CollectionAction {
	if o == nil || IsNil(o.Actions) {
		var ret []CollectionAction
		return ret
	}
	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionPermissionRule) GetActionsOk() ([]CollectionAction, bool) {
	if o == nil || IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *CollectionPermissionRule) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given []CollectionAction and assigns it to the Actions field.
func (o *CollectionPermissionRule) SetActions(v []CollectionAction) {
	o.Actions = v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *CollectionPermissionRule) GetConditions() map[string]interface{} {
	if o == nil || IsNil(o.Conditions) {
		var ret map[string]interface{}
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionPermissionRule) GetConditionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Conditions) {
		return map[string]interface{}{}, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *CollectionPermissionRule) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given map[string]interface{} and assigns it to the Conditions field.
func (o *CollectionPermissionRule) SetConditions(v map[string]interface{}) {
	o.Conditions = v
}

func (o CollectionPermissionRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollectionPermissionRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Actions) {
		toSerialize["actions"] = o.Actions
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	return toSerialize, nil
}

type NullableCollectionPermissionRule struct {
	value *CollectionPermissionRule
	isSet bool
}

func (v NullableCollectionPermissionRule) Get() *CollectionPermissionRule {
	return v.value
}

func (v *NullableCollectionPermissionRule) Set(val *CollectionPermissionRule) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionPermissionRule) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionPermissionRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionPermissionRule(val *CollectionPermissionRule) *NullableCollectionPermissionRule {
	return &NullableCollectionPermissionRule{value: val, isSet: true}
}

func (v NullableCollectionPermissionRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionPermissionRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


