/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.10
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BroadcastNonCustodialTransactionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BroadcastNonCustodialTransactionRequest{}

// BroadcastNonCustodialTransactionRequest struct for BroadcastNonCustodialTransactionRequest
type BroadcastNonCustodialTransactionRequest struct {
	// Blockchain for broadcast (EVM, UTXO, or chain-specific)
	Chain string `json:"chain"`
	// Fully signed transaction (hex string)
	SignedTx string `json:"signedTx"`
	// Address that signed the transaction (must be registered)
	FromAddress string `json:"fromAddress"`
}

type _BroadcastNonCustodialTransactionRequest BroadcastNonCustodialTransactionRequest

// NewBroadcastNonCustodialTransactionRequest instantiates a new BroadcastNonCustodialTransactionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBroadcastNonCustodialTransactionRequest(chain string, signedTx string, fromAddress string) *BroadcastNonCustodialTransactionRequest {
	this := BroadcastNonCustodialTransactionRequest{}
	this.Chain = chain
	this.SignedTx = signedTx
	this.FromAddress = fromAddress
	return &this
}

// NewBroadcastNonCustodialTransactionRequestWithDefaults instantiates a new BroadcastNonCustodialTransactionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBroadcastNonCustodialTransactionRequestWithDefaults() *BroadcastNonCustodialTransactionRequest {
	this := BroadcastNonCustodialTransactionRequest{}
	return &this
}

// GetChain returns the Chain field value
func (o *BroadcastNonCustodialTransactionRequest) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *BroadcastNonCustodialTransactionRequest) GetChainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *BroadcastNonCustodialTransactionRequest) SetChain(v string) {
	o.Chain = v
}

// GetSignedTx returns the SignedTx field value
func (o *BroadcastNonCustodialTransactionRequest) GetSignedTx() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignedTx
}

// GetSignedTxOk returns a tuple with the SignedTx field value
// and a boolean to check if the value has been set.
func (o *BroadcastNonCustodialTransactionRequest) GetSignedTxOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignedTx, true
}

// SetSignedTx sets field value
func (o *BroadcastNonCustodialTransactionRequest) SetSignedTx(v string) {
	o.SignedTx = v
}

// GetFromAddress returns the FromAddress field value
func (o *BroadcastNonCustodialTransactionRequest) GetFromAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromAddress
}

// GetFromAddressOk returns a tuple with the FromAddress field value
// and a boolean to check if the value has been set.
func (o *BroadcastNonCustodialTransactionRequest) GetFromAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromAddress, true
}

// SetFromAddress sets field value
func (o *BroadcastNonCustodialTransactionRequest) SetFromAddress(v string) {
	o.FromAddress = v
}

func (o BroadcastNonCustodialTransactionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BroadcastNonCustodialTransactionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chain"] = o.Chain
	toSerialize["signedTx"] = o.SignedTx
	toSerialize["fromAddress"] = o.FromAddress
	return toSerialize, nil
}

func (o *BroadcastNonCustodialTransactionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"chain",
		"signedTx",
		"fromAddress",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBroadcastNonCustodialTransactionRequest := _BroadcastNonCustodialTransactionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBroadcastNonCustodialTransactionRequest)

	if err != nil {
		return err
	}

	*o = BroadcastNonCustodialTransactionRequest(varBroadcastNonCustodialTransactionRequest)

	return err
}

type NullableBroadcastNonCustodialTransactionRequest struct {
	value *BroadcastNonCustodialTransactionRequest
	isSet bool
}

func (v NullableBroadcastNonCustodialTransactionRequest) Get() *BroadcastNonCustodialTransactionRequest {
	return v.value
}

func (v *NullableBroadcastNonCustodialTransactionRequest) Set(val *BroadcastNonCustodialTransactionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBroadcastNonCustodialTransactionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBroadcastNonCustodialTransactionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBroadcastNonCustodialTransactionRequest(val *BroadcastNonCustodialTransactionRequest) *NullableBroadcastNonCustodialTransactionRequest {
	return &NullableBroadcastNonCustodialTransactionRequest{value: val, isSet: true}
}

func (v NullableBroadcastNonCustodialTransactionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBroadcastNonCustodialTransactionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


