/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.7
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EstimateNetworkFeeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EstimateNetworkFeeRequest{}

// EstimateNetworkFeeRequest struct for EstimateNetworkFeeRequest
type EstimateNetworkFeeRequest struct {
	// Currency code
	Currency string `json:"currency"`
	// Transaction amount (used for display; fee is chain-based)
	Amount float32 `json:"amount"`
	// Required for USDT; network on which USDT is sent
	Network *string `json:"network,omitempty"`
}

type _EstimateNetworkFeeRequest EstimateNetworkFeeRequest

// NewEstimateNetworkFeeRequest instantiates a new EstimateNetworkFeeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEstimateNetworkFeeRequest(currency string, amount float32) *EstimateNetworkFeeRequest {
	this := EstimateNetworkFeeRequest{}
	this.Currency = currency
	this.Amount = amount
	return &this
}

// NewEstimateNetworkFeeRequestWithDefaults instantiates a new EstimateNetworkFeeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEstimateNetworkFeeRequestWithDefaults() *EstimateNetworkFeeRequest {
	this := EstimateNetworkFeeRequest{}
	return &this
}

// GetCurrency returns the Currency field value
func (o *EstimateNetworkFeeRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *EstimateNetworkFeeRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *EstimateNetworkFeeRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetAmount returns the Amount field value
func (o *EstimateNetworkFeeRequest) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *EstimateNetworkFeeRequest) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *EstimateNetworkFeeRequest) SetAmount(v float32) {
	o.Amount = v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *EstimateNetworkFeeRequest) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstimateNetworkFeeRequest) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *EstimateNetworkFeeRequest) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *EstimateNetworkFeeRequest) SetNetwork(v string) {
	o.Network = &v
}

func (o EstimateNetworkFeeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EstimateNetworkFeeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["currency"] = o.Currency
	toSerialize["amount"] = o.Amount
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	return toSerialize, nil
}

func (o *EstimateNetworkFeeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currency",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEstimateNetworkFeeRequest := _EstimateNetworkFeeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEstimateNetworkFeeRequest)

	if err != nil {
		return err
	}

	*o = EstimateNetworkFeeRequest(varEstimateNetworkFeeRequest)

	return err
}

type NullableEstimateNetworkFeeRequest struct {
	value *EstimateNetworkFeeRequest
	isSet bool
}

func (v NullableEstimateNetworkFeeRequest) Get() *EstimateNetworkFeeRequest {
	return v.value
}

func (v *NullableEstimateNetworkFeeRequest) Set(val *EstimateNetworkFeeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEstimateNetworkFeeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEstimateNetworkFeeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEstimateNetworkFeeRequest(val *EstimateNetworkFeeRequest) *NullableEstimateNetworkFeeRequest {
	return &NullableEstimateNetworkFeeRequest{value: val, isSet: true}
}

func (v NullableEstimateNetworkFeeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEstimateNetworkFeeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


