/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave for fiat (platform subscriptions and payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.12
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the SearchGetAnalytics200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchGetAnalytics200Response{}

// SearchGetAnalytics200Response struct for SearchGetAnalytics200Response
type SearchGetAnalytics200Response struct {
	TotalSearches *int32 `json:"totalSearches,omitempty"`
	TopQueries []SearchGetAnalytics200ResponseTopQueriesInner `json:"topQueries,omitempty"`
	SearchesByCollection map[string]interface{} `json:"searchesByCollection,omitempty"`
	AverageResponseTime *float32 `json:"averageResponseTime,omitempty"`
}

// NewSearchGetAnalytics200Response instantiates a new SearchGetAnalytics200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchGetAnalytics200Response() *SearchGetAnalytics200Response {
	this := SearchGetAnalytics200Response{}
	return &this
}

// NewSearchGetAnalytics200ResponseWithDefaults instantiates a new SearchGetAnalytics200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchGetAnalytics200ResponseWithDefaults() *SearchGetAnalytics200Response {
	this := SearchGetAnalytics200Response{}
	return &this
}

// GetTotalSearches returns the TotalSearches field value if set, zero value otherwise.
func (o *SearchGetAnalytics200Response) GetTotalSearches() int32 {
	if o == nil || IsNil(o.TotalSearches) {
		var ret int32
		return ret
	}
	return *o.TotalSearches
}

// GetTotalSearchesOk returns a tuple with the TotalSearches field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchGetAnalytics200Response) GetTotalSearchesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalSearches) {
		return nil, false
	}
	return o.TotalSearches, true
}

// HasTotalSearches returns a boolean if a field has been set.
func (o *SearchGetAnalytics200Response) HasTotalSearches() bool {
	if o != nil && !IsNil(o.TotalSearches) {
		return true
	}

	return false
}

// SetTotalSearches gets a reference to the given int32 and assigns it to the TotalSearches field.
func (o *SearchGetAnalytics200Response) SetTotalSearches(v int32) {
	o.TotalSearches = &v
}

// GetTopQueries returns the TopQueries field value if set, zero value otherwise.
func (o *SearchGetAnalytics200Response) GetTopQueries() []SearchGetAnalytics200ResponseTopQueriesInner {
	if o == nil || IsNil(o.TopQueries) {
		var ret []SearchGetAnalytics200ResponseTopQueriesInner
		return ret
	}
	return o.TopQueries
}

// GetTopQueriesOk returns a tuple with the TopQueries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchGetAnalytics200Response) GetTopQueriesOk() ([]SearchGetAnalytics200ResponseTopQueriesInner, bool) {
	if o == nil || IsNil(o.TopQueries) {
		return nil, false
	}
	return o.TopQueries, true
}

// HasTopQueries returns a boolean if a field has been set.
func (o *SearchGetAnalytics200Response) HasTopQueries() bool {
	if o != nil && !IsNil(o.TopQueries) {
		return true
	}

	return false
}

// SetTopQueries gets a reference to the given []SearchGetAnalytics200ResponseTopQueriesInner and assigns it to the TopQueries field.
func (o *SearchGetAnalytics200Response) SetTopQueries(v []SearchGetAnalytics200ResponseTopQueriesInner) {
	o.TopQueries = v
}

// GetSearchesByCollection returns the SearchesByCollection field value if set, zero value otherwise.
func (o *SearchGetAnalytics200Response) GetSearchesByCollection() map[string]interface{} {
	if o == nil || IsNil(o.SearchesByCollection) {
		var ret map[string]interface{}
		return ret
	}
	return o.SearchesByCollection
}

// GetSearchesByCollectionOk returns a tuple with the SearchesByCollection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchGetAnalytics200Response) GetSearchesByCollectionOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.SearchesByCollection) {
		return map[string]interface{}{}, false
	}
	return o.SearchesByCollection, true
}

// HasSearchesByCollection returns a boolean if a field has been set.
func (o *SearchGetAnalytics200Response) HasSearchesByCollection() bool {
	if o != nil && !IsNil(o.SearchesByCollection) {
		return true
	}

	return false
}

// SetSearchesByCollection gets a reference to the given map[string]interface{} and assigns it to the SearchesByCollection field.
func (o *SearchGetAnalytics200Response) SetSearchesByCollection(v map[string]interface{}) {
	o.SearchesByCollection = v
}

// GetAverageResponseTime returns the AverageResponseTime field value if set, zero value otherwise.
func (o *SearchGetAnalytics200Response) GetAverageResponseTime() float32 {
	if o == nil || IsNil(o.AverageResponseTime) {
		var ret float32
		return ret
	}
	return *o.AverageResponseTime
}

// GetAverageResponseTimeOk returns a tuple with the AverageResponseTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchGetAnalytics200Response) GetAverageResponseTimeOk() (*float32, bool) {
	if o == nil || IsNil(o.AverageResponseTime) {
		return nil, false
	}
	return o.AverageResponseTime, true
}

// HasAverageResponseTime returns a boolean if a field has been set.
func (o *SearchGetAnalytics200Response) HasAverageResponseTime() bool {
	if o != nil && !IsNil(o.AverageResponseTime) {
		return true
	}

	return false
}

// SetAverageResponseTime gets a reference to the given float32 and assigns it to the AverageResponseTime field.
func (o *SearchGetAnalytics200Response) SetAverageResponseTime(v float32) {
	o.AverageResponseTime = &v
}

func (o SearchGetAnalytics200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchGetAnalytics200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalSearches) {
		toSerialize["totalSearches"] = o.TotalSearches
	}
	if !IsNil(o.TopQueries) {
		toSerialize["topQueries"] = o.TopQueries
	}
	if !IsNil(o.SearchesByCollection) {
		toSerialize["searchesByCollection"] = o.SearchesByCollection
	}
	if !IsNil(o.AverageResponseTime) {
		toSerialize["averageResponseTime"] = o.AverageResponseTime
	}
	return toSerialize, nil
}

type NullableSearchGetAnalytics200Response struct {
	value *SearchGetAnalytics200Response
	isSet bool
}

func (v NullableSearchGetAnalytics200Response) Get() *SearchGetAnalytics200Response {
	return v.value
}

func (v *NullableSearchGetAnalytics200Response) Set(val *SearchGetAnalytics200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchGetAnalytics200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchGetAnalytics200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchGetAnalytics200Response(val *SearchGetAnalytics200Response) *NullableSearchGetAnalytics200Response {
	return &NullableSearchGetAnalytics200Response{value: val, isSet: true}
}

func (v NullableSearchGetAnalytics200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchGetAnalytics200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


