/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise: custom domains under `GET/POST/PATCH/DELETE /api/orgs/{orgId}/projects/{projectId}/domains` (plan `features.customDomainAllowed`); stable error codes `hostname_in_use`, `domain_limit_reached`, `domain_rate_limited`, `custom_domain_not_allowed`, `provision_conflict`, `not_enterprise_plan`; internal `POST /internal/provision-enterprise` with header `X-Internal-Api-Key`; responses on platform host may include `X-Mudbase-Warning: use_dedicated_api` for dedicated orgs. 

API version: 1.2.10
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthRegisterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthRegisterRequest{}

// AuthRegisterRequest struct for AuthRegisterRequest
type AuthRegisterRequest struct {
	Email string `json:"email"`
	Password string `json:"password"`
	FirstName string `json:"firstName"`
	LastName string `json:"lastName"`
	ProjectId string `json:"projectId"`
}

type _AuthRegisterRequest AuthRegisterRequest

// NewAuthRegisterRequest instantiates a new AuthRegisterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthRegisterRequest(email string, password string, firstName string, lastName string, projectId string) *AuthRegisterRequest {
	this := AuthRegisterRequest{}
	this.Email = email
	this.Password = password
	this.FirstName = firstName
	this.LastName = lastName
	this.ProjectId = projectId
	return &this
}

// NewAuthRegisterRequestWithDefaults instantiates a new AuthRegisterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthRegisterRequestWithDefaults() *AuthRegisterRequest {
	this := AuthRegisterRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *AuthRegisterRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AuthRegisterRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AuthRegisterRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *AuthRegisterRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *AuthRegisterRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *AuthRegisterRequest) SetPassword(v string) {
	o.Password = v
}

// GetFirstName returns the FirstName field value
func (o *AuthRegisterRequest) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *AuthRegisterRequest) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *AuthRegisterRequest) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value
func (o *AuthRegisterRequest) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *AuthRegisterRequest) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *AuthRegisterRequest) SetLastName(v string) {
	o.LastName = v
}

// GetProjectId returns the ProjectId field value
func (o *AuthRegisterRequest) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *AuthRegisterRequest) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *AuthRegisterRequest) SetProjectId(v string) {
	o.ProjectId = v
}

func (o AuthRegisterRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthRegisterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	toSerialize["firstName"] = o.FirstName
	toSerialize["lastName"] = o.LastName
	toSerialize["projectId"] = o.ProjectId
	return toSerialize, nil
}

func (o *AuthRegisterRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
		"firstName",
		"lastName",
		"projectId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthRegisterRequest := _AuthRegisterRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthRegisterRequest)

	if err != nil {
		return err
	}

	*o = AuthRegisterRequest(varAuthRegisterRequest)

	return err
}

type NullableAuthRegisterRequest struct {
	value *AuthRegisterRequest
	isSet bool
}

func (v NullableAuthRegisterRequest) Get() *AuthRegisterRequest {
	return v.value
}

func (v *NullableAuthRegisterRequest) Set(val *AuthRegisterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthRegisterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthRegisterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthRegisterRequest(val *AuthRegisterRequest) *NullableAuthRegisterRequest {
	return &NullableAuthRegisterRequest{value: val, isSet: true}
}

func (v NullableAuthRegisterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthRegisterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


