/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.9
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the DeleteBackup200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteBackup200Response{}

// DeleteBackup200Response struct for DeleteBackup200Response
type DeleteBackup200Response struct {
	Message *string `json:"message,omitempty"`
}

// NewDeleteBackup200Response instantiates a new DeleteBackup200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteBackup200Response() *DeleteBackup200Response {
	this := DeleteBackup200Response{}
	return &this
}

// NewDeleteBackup200ResponseWithDefaults instantiates a new DeleteBackup200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteBackup200ResponseWithDefaults() *DeleteBackup200Response {
	this := DeleteBackup200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DeleteBackup200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteBackup200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DeleteBackup200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DeleteBackup200Response) SetMessage(v string) {
	o.Message = &v
}

func (o DeleteBackup200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteBackup200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableDeleteBackup200Response struct {
	value *DeleteBackup200Response
	isSet bool
}

func (v NullableDeleteBackup200Response) Get() *DeleteBackup200Response {
	return v.value
}

func (v *NullableDeleteBackup200Response) Set(val *DeleteBackup200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteBackup200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteBackup200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteBackup200Response(val *DeleteBackup200Response) *NullableDeleteBackup200Response {
	return &NullableDeleteBackup200Response{value: val, isSet: true}
}

func (v NullableDeleteBackup200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteBackup200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


