/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.9
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
	"time"
)

// checks if the BillingVerifyPayment200ResponseDataSubscription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingVerifyPayment200ResponseDataSubscription{}

// BillingVerifyPayment200ResponseDataSubscription struct for BillingVerifyPayment200ResponseDataSubscription
type BillingVerifyPayment200ResponseDataSubscription struct {
	Id *string `json:"_id,omitempty"`
	Status *string `json:"status,omitempty"`
	Plan *string `json:"plan,omitempty"`
	CurrentPeriodEnd *time.Time `json:"currentPeriodEnd,omitempty"`
}

// NewBillingVerifyPayment200ResponseDataSubscription instantiates a new BillingVerifyPayment200ResponseDataSubscription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingVerifyPayment200ResponseDataSubscription() *BillingVerifyPayment200ResponseDataSubscription {
	this := BillingVerifyPayment200ResponseDataSubscription{}
	return &this
}

// NewBillingVerifyPayment200ResponseDataSubscriptionWithDefaults instantiates a new BillingVerifyPayment200ResponseDataSubscription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingVerifyPayment200ResponseDataSubscriptionWithDefaults() *BillingVerifyPayment200ResponseDataSubscription {
	this := BillingVerifyPayment200ResponseDataSubscription{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BillingVerifyPayment200ResponseDataSubscription) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingVerifyPayment200ResponseDataSubscription) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BillingVerifyPayment200ResponseDataSubscription) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BillingVerifyPayment200ResponseDataSubscription) SetId(v string) {
	o.Id = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BillingVerifyPayment200ResponseDataSubscription) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingVerifyPayment200ResponseDataSubscription) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BillingVerifyPayment200ResponseDataSubscription) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *BillingVerifyPayment200ResponseDataSubscription) SetStatus(v string) {
	o.Status = &v
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *BillingVerifyPayment200ResponseDataSubscription) GetPlan() string {
	if o == nil || IsNil(o.Plan) {
		var ret string
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingVerifyPayment200ResponseDataSubscription) GetPlanOk() (*string, bool) {
	if o == nil || IsNil(o.Plan) {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *BillingVerifyPayment200ResponseDataSubscription) HasPlan() bool {
	if o != nil && !IsNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given string and assigns it to the Plan field.
func (o *BillingVerifyPayment200ResponseDataSubscription) SetPlan(v string) {
	o.Plan = &v
}

// GetCurrentPeriodEnd returns the CurrentPeriodEnd field value if set, zero value otherwise.
func (o *BillingVerifyPayment200ResponseDataSubscription) GetCurrentPeriodEnd() time.Time {
	if o == nil || IsNil(o.CurrentPeriodEnd) {
		var ret time.Time
		return ret
	}
	return *o.CurrentPeriodEnd
}

// GetCurrentPeriodEndOk returns a tuple with the CurrentPeriodEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingVerifyPayment200ResponseDataSubscription) GetCurrentPeriodEndOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CurrentPeriodEnd) {
		return nil, false
	}
	return o.CurrentPeriodEnd, true
}

// HasCurrentPeriodEnd returns a boolean if a field has been set.
func (o *BillingVerifyPayment200ResponseDataSubscription) HasCurrentPeriodEnd() bool {
	if o != nil && !IsNil(o.CurrentPeriodEnd) {
		return true
	}

	return false
}

// SetCurrentPeriodEnd gets a reference to the given time.Time and assigns it to the CurrentPeriodEnd field.
func (o *BillingVerifyPayment200ResponseDataSubscription) SetCurrentPeriodEnd(v time.Time) {
	o.CurrentPeriodEnd = &v
}

func (o BillingVerifyPayment200ResponseDataSubscription) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingVerifyPayment200ResponseDataSubscription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["_id"] = o.Id
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}
	if !IsNil(o.CurrentPeriodEnd) {
		toSerialize["currentPeriodEnd"] = o.CurrentPeriodEnd
	}
	return toSerialize, nil
}

type NullableBillingVerifyPayment200ResponseDataSubscription struct {
	value *BillingVerifyPayment200ResponseDataSubscription
	isSet bool
}

func (v NullableBillingVerifyPayment200ResponseDataSubscription) Get() *BillingVerifyPayment200ResponseDataSubscription {
	return v.value
}

func (v *NullableBillingVerifyPayment200ResponseDataSubscription) Set(val *BillingVerifyPayment200ResponseDataSubscription) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingVerifyPayment200ResponseDataSubscription) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingVerifyPayment200ResponseDataSubscription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingVerifyPayment200ResponseDataSubscription(val *BillingVerifyPayment200ResponseDataSubscription) *NullableBillingVerifyPayment200ResponseDataSubscription {
	return &NullableBillingVerifyPayment200ResponseDataSubscription{value: val, isSet: true}
}

func (v NullableBillingVerifyPayment200ResponseDataSubscription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingVerifyPayment200ResponseDataSubscription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


