/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.7
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the GetAvailableOAuthProviders200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAvailableOAuthProviders200Response{}

// GetAvailableOAuthProviders200Response struct for GetAvailableOAuthProviders200Response
type GetAvailableOAuthProviders200Response struct {
	Providers []GetAvailableOAuthProviders200ResponseProvidersInner `json:"providers,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewGetAvailableOAuthProviders200Response instantiates a new GetAvailableOAuthProviders200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAvailableOAuthProviders200Response() *GetAvailableOAuthProviders200Response {
	this := GetAvailableOAuthProviders200Response{}
	return &this
}

// NewGetAvailableOAuthProviders200ResponseWithDefaults instantiates a new GetAvailableOAuthProviders200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAvailableOAuthProviders200ResponseWithDefaults() *GetAvailableOAuthProviders200Response {
	this := GetAvailableOAuthProviders200Response{}
	return &this
}

// GetProviders returns the Providers field value if set, zero value otherwise.
func (o *GetAvailableOAuthProviders200Response) GetProviders() []GetAvailableOAuthProviders200ResponseProvidersInner {
	if o == nil || IsNil(o.Providers) {
		var ret []GetAvailableOAuthProviders200ResponseProvidersInner
		return ret
	}
	return o.Providers
}

// GetProvidersOk returns a tuple with the Providers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAvailableOAuthProviders200Response) GetProvidersOk() ([]GetAvailableOAuthProviders200ResponseProvidersInner, bool) {
	if o == nil || IsNil(o.Providers) {
		return nil, false
	}
	return o.Providers, true
}

// HasProviders returns a boolean if a field has been set.
func (o *GetAvailableOAuthProviders200Response) HasProviders() bool {
	if o != nil && !IsNil(o.Providers) {
		return true
	}

	return false
}

// SetProviders gets a reference to the given []GetAvailableOAuthProviders200ResponseProvidersInner and assigns it to the Providers field.
func (o *GetAvailableOAuthProviders200Response) SetProviders(v []GetAvailableOAuthProviders200ResponseProvidersInner) {
	o.Providers = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetAvailableOAuthProviders200Response) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAvailableOAuthProviders200Response) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetAvailableOAuthProviders200Response) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetAvailableOAuthProviders200Response) SetTotal(v int32) {
	o.Total = &v
}

func (o GetAvailableOAuthProviders200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAvailableOAuthProviders200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Providers) {
		toSerialize["providers"] = o.Providers
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableGetAvailableOAuthProviders200Response struct {
	value *GetAvailableOAuthProviders200Response
	isSet bool
}

func (v NullableGetAvailableOAuthProviders200Response) Get() *GetAvailableOAuthProviders200Response {
	return v.value
}

func (v *NullableGetAvailableOAuthProviders200Response) Set(val *GetAvailableOAuthProviders200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAvailableOAuthProviders200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAvailableOAuthProviders200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAvailableOAuthProviders200Response(val *GetAvailableOAuthProviders200Response) *NullableGetAvailableOAuthProviders200Response {
	return &NullableGetAvailableOAuthProviders200Response{value: val, isSet: true}
}

func (v NullableGetAvailableOAuthProviders200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAvailableOAuthProviders200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


