/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.6
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the GetChatMessages200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetChatMessages200ResponseData{}

// GetChatMessages200ResponseData struct for GetChatMessages200ResponseData
type GetChatMessages200ResponseData struct {
	Messages []GetChatMessages200ResponseDataMessagesInner `json:"messages,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewGetChatMessages200ResponseData instantiates a new GetChatMessages200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetChatMessages200ResponseData() *GetChatMessages200ResponseData {
	this := GetChatMessages200ResponseData{}
	return &this
}

// NewGetChatMessages200ResponseDataWithDefaults instantiates a new GetChatMessages200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetChatMessages200ResponseDataWithDefaults() *GetChatMessages200ResponseData {
	this := GetChatMessages200ResponseData{}
	return &this
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *GetChatMessages200ResponseData) GetMessages() []GetChatMessages200ResponseDataMessagesInner {
	if o == nil || IsNil(o.Messages) {
		var ret []GetChatMessages200ResponseDataMessagesInner
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChatMessages200ResponseData) GetMessagesOk() ([]GetChatMessages200ResponseDataMessagesInner, bool) {
	if o == nil || IsNil(o.Messages) {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *GetChatMessages200ResponseData) HasMessages() bool {
	if o != nil && !IsNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []GetChatMessages200ResponseDataMessagesInner and assigns it to the Messages field.
func (o *GetChatMessages200ResponseData) SetMessages(v []GetChatMessages200ResponseDataMessagesInner) {
	o.Messages = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetChatMessages200ResponseData) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChatMessages200ResponseData) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetChatMessages200ResponseData) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetChatMessages200ResponseData) SetTotal(v int32) {
	o.Total = &v
}

func (o GetChatMessages200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetChatMessages200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Messages) {
		toSerialize["messages"] = o.Messages
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableGetChatMessages200ResponseData struct {
	value *GetChatMessages200ResponseData
	isSet bool
}

func (v NullableGetChatMessages200ResponseData) Get() *GetChatMessages200ResponseData {
	return v.value
}

func (v *NullableGetChatMessages200ResponseData) Set(val *GetChatMessages200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetChatMessages200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetChatMessages200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetChatMessages200ResponseData(val *GetChatMessages200ResponseData) *NullableGetChatMessages200ResponseData {
	return &NullableGetChatMessages200ResponseData{value: val, isSet: true}
}

func (v NullableGetChatMessages200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetChatMessages200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


