/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave for fiat (platform subscriptions and payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.11
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the StorageConfirmUpload400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageConfirmUpload400Response{}

// StorageConfirmUpload400Response struct for StorageConfirmUpload400Response
type StorageConfirmUpload400Response struct {
	Message *string `json:"message,omitempty"`
	Details map[string]interface{} `json:"details,omitempty"`
}

// NewStorageConfirmUpload400Response instantiates a new StorageConfirmUpload400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageConfirmUpload400Response() *StorageConfirmUpload400Response {
	this := StorageConfirmUpload400Response{}
	return &this
}

// NewStorageConfirmUpload400ResponseWithDefaults instantiates a new StorageConfirmUpload400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageConfirmUpload400ResponseWithDefaults() *StorageConfirmUpload400Response {
	this := StorageConfirmUpload400Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *StorageConfirmUpload400Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageConfirmUpload400Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *StorageConfirmUpload400Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *StorageConfirmUpload400Response) SetMessage(v string) {
	o.Message = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *StorageConfirmUpload400Response) GetDetails() map[string]interface{} {
	if o == nil || IsNil(o.Details) {
		var ret map[string]interface{}
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageConfirmUpload400Response) GetDetailsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Details) {
		return map[string]interface{}{}, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *StorageConfirmUpload400Response) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given map[string]interface{} and assigns it to the Details field.
func (o *StorageConfirmUpload400Response) SetDetails(v map[string]interface{}) {
	o.Details = v
}

func (o StorageConfirmUpload400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageConfirmUpload400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	return toSerialize, nil
}

type NullableStorageConfirmUpload400Response struct {
	value *StorageConfirmUpload400Response
	isSet bool
}

func (v NullableStorageConfirmUpload400Response) Get() *StorageConfirmUpload400Response {
	return v.value
}

func (v *NullableStorageConfirmUpload400Response) Set(val *StorageConfirmUpload400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageConfirmUpload400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageConfirmUpload400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageConfirmUpload400Response(val *StorageConfirmUpload400Response) *NullableStorageConfirmUpload400Response {
	return &NullableStorageConfirmUpload400Response{value: val, isSet: true}
}

func (v NullableStorageConfirmUpload400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageConfirmUpload400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


