/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.3
Contact: support@dev.mudbase
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
	"time"
)

// checks if the SignedUrlResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignedUrlResponse{}

// SignedUrlResponse Signed URL for temporary file access (url, expiresAt or expiresIn).
type SignedUrlResponse struct {
	Success *bool `json:"success,omitempty"`
	// Signed URL for file access
	Url *string `json:"url,omitempty"`
	// Expiration time of the signed URL (optional - some endpoints return expiresIn instead)
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	// Time-to-live in seconds for the signed URL (optional)
	ExpiresIn *int32 `json:"expiresIn,omitempty"`
}

// NewSignedUrlResponse instantiates a new SignedUrlResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignedUrlResponse() *SignedUrlResponse {
	this := SignedUrlResponse{}
	return &this
}

// NewSignedUrlResponseWithDefaults instantiates a new SignedUrlResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignedUrlResponseWithDefaults() *SignedUrlResponse {
	this := SignedUrlResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *SignedUrlResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignedUrlResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *SignedUrlResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *SignedUrlResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *SignedUrlResponse) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignedUrlResponse) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *SignedUrlResponse) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *SignedUrlResponse) SetUrl(v string) {
	o.Url = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *SignedUrlResponse) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignedUrlResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *SignedUrlResponse) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *SignedUrlResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *SignedUrlResponse) GetExpiresIn() int32 {
	if o == nil || IsNil(o.ExpiresIn) {
		var ret int32
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignedUrlResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpiresIn) {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *SignedUrlResponse) HasExpiresIn() bool {
	if o != nil && !IsNil(o.ExpiresIn) {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given int32 and assigns it to the ExpiresIn field.
func (o *SignedUrlResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = &v
}

func (o SignedUrlResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignedUrlResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if !IsNil(o.ExpiresIn) {
		toSerialize["expiresIn"] = o.ExpiresIn
	}
	return toSerialize, nil
}

type NullableSignedUrlResponse struct {
	value *SignedUrlResponse
	isSet bool
}

func (v NullableSignedUrlResponse) Get() *SignedUrlResponse {
	return v.value
}

func (v *NullableSignedUrlResponse) Set(val *SignedUrlResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSignedUrlResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSignedUrlResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignedUrlResponse(val *SignedUrlResponse) *NullableSignedUrlResponse {
	return &NullableSignedUrlResponse{value: val, isSet: true}
}

func (v NullableSignedUrlResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignedUrlResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


