/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.6
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
	"time"
)

// checks if the GetChatE2eeParticipantKeys200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetChatE2eeParticipantKeys200ResponseDataInner{}

// GetChatE2eeParticipantKeys200ResponseDataInner struct for GetChatE2eeParticipantKeys200ResponseDataInner
type GetChatE2eeParticipantKeys200ResponseDataInner struct {
	UserId *string `json:"userId,omitempty"`
	IdentityPublicKey *string `json:"identityPublicKey,omitempty"`
	KeyVersion *int32 `json:"keyVersion,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewGetChatE2eeParticipantKeys200ResponseDataInner instantiates a new GetChatE2eeParticipantKeys200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetChatE2eeParticipantKeys200ResponseDataInner() *GetChatE2eeParticipantKeys200ResponseDataInner {
	this := GetChatE2eeParticipantKeys200ResponseDataInner{}
	return &this
}

// NewGetChatE2eeParticipantKeys200ResponseDataInnerWithDefaults instantiates a new GetChatE2eeParticipantKeys200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetChatE2eeParticipantKeys200ResponseDataInnerWithDefaults() *GetChatE2eeParticipantKeys200ResponseDataInner {
	this := GetChatE2eeParticipantKeys200ResponseDataInner{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) SetUserId(v string) {
	o.UserId = &v
}

// GetIdentityPublicKey returns the IdentityPublicKey field value if set, zero value otherwise.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) GetIdentityPublicKey() string {
	if o == nil || IsNil(o.IdentityPublicKey) {
		var ret string
		return ret
	}
	return *o.IdentityPublicKey
}

// GetIdentityPublicKeyOk returns a tuple with the IdentityPublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) GetIdentityPublicKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IdentityPublicKey) {
		return nil, false
	}
	return o.IdentityPublicKey, true
}

// HasIdentityPublicKey returns a boolean if a field has been set.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) HasIdentityPublicKey() bool {
	if o != nil && !IsNil(o.IdentityPublicKey) {
		return true
	}

	return false
}

// SetIdentityPublicKey gets a reference to the given string and assigns it to the IdentityPublicKey field.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) SetIdentityPublicKey(v string) {
	o.IdentityPublicKey = &v
}

// GetKeyVersion returns the KeyVersion field value if set, zero value otherwise.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) GetKeyVersion() int32 {
	if o == nil || IsNil(o.KeyVersion) {
		var ret int32
		return ret
	}
	return *o.KeyVersion
}

// GetKeyVersionOk returns a tuple with the KeyVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) GetKeyVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.KeyVersion) {
		return nil, false
	}
	return o.KeyVersion, true
}

// HasKeyVersion returns a boolean if a field has been set.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) HasKeyVersion() bool {
	if o != nil && !IsNil(o.KeyVersion) {
		return true
	}

	return false
}

// SetKeyVersion gets a reference to the given int32 and assigns it to the KeyVersion field.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) SetKeyVersion(v int32) {
	o.KeyVersion = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *GetChatE2eeParticipantKeys200ResponseDataInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o GetChatE2eeParticipantKeys200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetChatE2eeParticipantKeys200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.IdentityPublicKey) {
		toSerialize["identityPublicKey"] = o.IdentityPublicKey
	}
	if !IsNil(o.KeyVersion) {
		toSerialize["keyVersion"] = o.KeyVersion
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableGetChatE2eeParticipantKeys200ResponseDataInner struct {
	value *GetChatE2eeParticipantKeys200ResponseDataInner
	isSet bool
}

func (v NullableGetChatE2eeParticipantKeys200ResponseDataInner) Get() *GetChatE2eeParticipantKeys200ResponseDataInner {
	return v.value
}

func (v *NullableGetChatE2eeParticipantKeys200ResponseDataInner) Set(val *GetChatE2eeParticipantKeys200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetChatE2eeParticipantKeys200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetChatE2eeParticipantKeys200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetChatE2eeParticipantKeys200ResponseDataInner(val *GetChatE2eeParticipantKeys200ResponseDataInner) *NullableGetChatE2eeParticipantKeys200ResponseDataInner {
	return &NullableGetChatE2eeParticipantKeys200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetChatE2eeParticipantKeys200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetChatE2eeParticipantKeys200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


