/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.10
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the ApiFilesDownloadFileIdGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiFilesDownloadFileIdGet200Response{}

// ApiFilesDownloadFileIdGet200Response struct for ApiFilesDownloadFileIdGet200Response
type ApiFilesDownloadFileIdGet200Response struct {
	Url *string `json:"url,omitempty"`
	// Seconds until the signed URL expires; null for public files.
	ExpiresIn NullableInt32 `json:"expiresIn,omitempty"`
	// Present and true only when the file is public.
	IsPublic *bool `json:"isPublic,omitempty"`
	// Present only for public files — explains the URL is permanent and unprotected.
	Warning *string `json:"warning,omitempty"`
}

// NewApiFilesDownloadFileIdGet200Response instantiates a new ApiFilesDownloadFileIdGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiFilesDownloadFileIdGet200Response() *ApiFilesDownloadFileIdGet200Response {
	this := ApiFilesDownloadFileIdGet200Response{}
	return &this
}

// NewApiFilesDownloadFileIdGet200ResponseWithDefaults instantiates a new ApiFilesDownloadFileIdGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiFilesDownloadFileIdGet200ResponseWithDefaults() *ApiFilesDownloadFileIdGet200Response {
	this := ApiFilesDownloadFileIdGet200Response{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ApiFilesDownloadFileIdGet200Response) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiFilesDownloadFileIdGet200Response) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ApiFilesDownloadFileIdGet200Response) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ApiFilesDownloadFileIdGet200Response) SetUrl(v string) {
	o.Url = &v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiFilesDownloadFileIdGet200Response) GetExpiresIn() int32 {
	if o == nil || IsNil(o.ExpiresIn.Get()) {
		var ret int32
		return ret
	}
	return *o.ExpiresIn.Get()
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiFilesDownloadFileIdGet200Response) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresIn.Get(), o.ExpiresIn.IsSet()
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *ApiFilesDownloadFileIdGet200Response) HasExpiresIn() bool {
	if o != nil && o.ExpiresIn.IsSet() {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given NullableInt32 and assigns it to the ExpiresIn field.
func (o *ApiFilesDownloadFileIdGet200Response) SetExpiresIn(v int32) {
	o.ExpiresIn.Set(&v)
}
// SetExpiresInNil sets the value for ExpiresIn to be an explicit nil
func (o *ApiFilesDownloadFileIdGet200Response) SetExpiresInNil() {
	o.ExpiresIn.Set(nil)
}

// UnsetExpiresIn ensures that no value is present for ExpiresIn, not even an explicit nil
func (o *ApiFilesDownloadFileIdGet200Response) UnsetExpiresIn() {
	o.ExpiresIn.Unset()
}

// GetIsPublic returns the IsPublic field value if set, zero value otherwise.
func (o *ApiFilesDownloadFileIdGet200Response) GetIsPublic() bool {
	if o == nil || IsNil(o.IsPublic) {
		var ret bool
		return ret
	}
	return *o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiFilesDownloadFileIdGet200Response) GetIsPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPublic) {
		return nil, false
	}
	return o.IsPublic, true
}

// HasIsPublic returns a boolean if a field has been set.
func (o *ApiFilesDownloadFileIdGet200Response) HasIsPublic() bool {
	if o != nil && !IsNil(o.IsPublic) {
		return true
	}

	return false
}

// SetIsPublic gets a reference to the given bool and assigns it to the IsPublic field.
func (o *ApiFilesDownloadFileIdGet200Response) SetIsPublic(v bool) {
	o.IsPublic = &v
}

// GetWarning returns the Warning field value if set, zero value otherwise.
func (o *ApiFilesDownloadFileIdGet200Response) GetWarning() string {
	if o == nil || IsNil(o.Warning) {
		var ret string
		return ret
	}
	return *o.Warning
}

// GetWarningOk returns a tuple with the Warning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiFilesDownloadFileIdGet200Response) GetWarningOk() (*string, bool) {
	if o == nil || IsNil(o.Warning) {
		return nil, false
	}
	return o.Warning, true
}

// HasWarning returns a boolean if a field has been set.
func (o *ApiFilesDownloadFileIdGet200Response) HasWarning() bool {
	if o != nil && !IsNil(o.Warning) {
		return true
	}

	return false
}

// SetWarning gets a reference to the given string and assigns it to the Warning field.
func (o *ApiFilesDownloadFileIdGet200Response) SetWarning(v string) {
	o.Warning = &v
}

func (o ApiFilesDownloadFileIdGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiFilesDownloadFileIdGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if o.ExpiresIn.IsSet() {
		toSerialize["expiresIn"] = o.ExpiresIn.Get()
	}
	if !IsNil(o.IsPublic) {
		toSerialize["isPublic"] = o.IsPublic
	}
	if !IsNil(o.Warning) {
		toSerialize["warning"] = o.Warning
	}
	return toSerialize, nil
}

type NullableApiFilesDownloadFileIdGet200Response struct {
	value *ApiFilesDownloadFileIdGet200Response
	isSet bool
}

func (v NullableApiFilesDownloadFileIdGet200Response) Get() *ApiFilesDownloadFileIdGet200Response {
	return v.value
}

func (v *NullableApiFilesDownloadFileIdGet200Response) Set(val *ApiFilesDownloadFileIdGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiFilesDownloadFileIdGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiFilesDownloadFileIdGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiFilesDownloadFileIdGet200Response(val *ApiFilesDownloadFileIdGet200Response) *NullableApiFilesDownloadFileIdGet200Response {
	return &NullableApiFilesDownloadFileIdGet200Response{value: val, isSet: true}
}

func (v NullableApiFilesDownloadFileIdGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiFilesDownloadFileIdGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


