/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.3
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the GetNonCustodialTransactions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNonCustodialTransactions200Response{}

// GetNonCustodialTransactions200Response struct for GetNonCustodialTransactions200Response
type GetNonCustodialTransactions200Response struct {
	Success *bool `json:"success,omitempty"`
	Data []WalletTransaction `json:"data,omitempty"`
	Pagination *GetTransactionHistory200ResponsePagination `json:"pagination,omitempty"`
}

// NewGetNonCustodialTransactions200Response instantiates a new GetNonCustodialTransactions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNonCustodialTransactions200Response() *GetNonCustodialTransactions200Response {
	this := GetNonCustodialTransactions200Response{}
	return &this
}

// NewGetNonCustodialTransactions200ResponseWithDefaults instantiates a new GetNonCustodialTransactions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNonCustodialTransactions200ResponseWithDefaults() *GetNonCustodialTransactions200Response {
	this := GetNonCustodialTransactions200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetNonCustodialTransactions200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNonCustodialTransactions200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetNonCustodialTransactions200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetNonCustodialTransactions200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetNonCustodialTransactions200Response) GetData() []WalletTransaction {
	if o == nil || IsNil(o.Data) {
		var ret []WalletTransaction
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNonCustodialTransactions200Response) GetDataOk() ([]WalletTransaction, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetNonCustodialTransactions200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []WalletTransaction and assigns it to the Data field.
func (o *GetNonCustodialTransactions200Response) SetData(v []WalletTransaction) {
	o.Data = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *GetNonCustodialTransactions200Response) GetPagination() GetTransactionHistory200ResponsePagination {
	if o == nil || IsNil(o.Pagination) {
		var ret GetTransactionHistory200ResponsePagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNonCustodialTransactions200Response) GetPaginationOk() (*GetTransactionHistory200ResponsePagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *GetNonCustodialTransactions200Response) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given GetTransactionHistory200ResponsePagination and assigns it to the Pagination field.
func (o *GetNonCustodialTransactions200Response) SetPagination(v GetTransactionHistory200ResponsePagination) {
	o.Pagination = &v
}

func (o GetNonCustodialTransactions200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNonCustodialTransactions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableGetNonCustodialTransactions200Response struct {
	value *GetNonCustodialTransactions200Response
	isSet bool
}

func (v NullableGetNonCustodialTransactions200Response) Get() *GetNonCustodialTransactions200Response {
	return v.value
}

func (v *NullableGetNonCustodialTransactions200Response) Set(val *GetNonCustodialTransactions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNonCustodialTransactions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNonCustodialTransactions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNonCustodialTransactions200Response(val *GetNonCustodialTransactions200Response) *NullableGetNonCustodialTransactions200Response {
	return &NullableGetNonCustodialTransactions200Response{value: val, isSet: true}
}

func (v NullableGetNonCustodialTransactions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNonCustodialTransactions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


