/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.6
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the PatchOrgDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchOrgDomainRequest{}

// PatchOrgDomainRequest struct for PatchOrgDomainRequest
type PatchOrgDomainRequest struct {
	// Org self-serve reset only; go-live is via admin activate.
	Status *string `json:"status,omitempty"`
	RegenerateToken *bool `json:"regenerateToken,omitempty"`
}

// NewPatchOrgDomainRequest instantiates a new PatchOrgDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchOrgDomainRequest() *PatchOrgDomainRequest {
	this := PatchOrgDomainRequest{}
	return &this
}

// NewPatchOrgDomainRequestWithDefaults instantiates a new PatchOrgDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchOrgDomainRequestWithDefaults() *PatchOrgDomainRequest {
	this := PatchOrgDomainRequest{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PatchOrgDomainRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchOrgDomainRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PatchOrgDomainRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PatchOrgDomainRequest) SetStatus(v string) {
	o.Status = &v
}

// GetRegenerateToken returns the RegenerateToken field value if set, zero value otherwise.
func (o *PatchOrgDomainRequest) GetRegenerateToken() bool {
	if o == nil || IsNil(o.RegenerateToken) {
		var ret bool
		return ret
	}
	return *o.RegenerateToken
}

// GetRegenerateTokenOk returns a tuple with the RegenerateToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchOrgDomainRequest) GetRegenerateTokenOk() (*bool, bool) {
	if o == nil || IsNil(o.RegenerateToken) {
		return nil, false
	}
	return o.RegenerateToken, true
}

// HasRegenerateToken returns a boolean if a field has been set.
func (o *PatchOrgDomainRequest) HasRegenerateToken() bool {
	if o != nil && !IsNil(o.RegenerateToken) {
		return true
	}

	return false
}

// SetRegenerateToken gets a reference to the given bool and assigns it to the RegenerateToken field.
func (o *PatchOrgDomainRequest) SetRegenerateToken(v bool) {
	o.RegenerateToken = &v
}

func (o PatchOrgDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchOrgDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.RegenerateToken) {
		toSerialize["regenerateToken"] = o.RegenerateToken
	}
	return toSerialize, nil
}

type NullablePatchOrgDomainRequest struct {
	value *PatchOrgDomainRequest
	isSet bool
}

func (v NullablePatchOrgDomainRequest) Get() *PatchOrgDomainRequest {
	return v.value
}

func (v *NullablePatchOrgDomainRequest) Set(val *PatchOrgDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchOrgDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchOrgDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchOrgDomainRequest(val *PatchOrgDomainRequest) *NullablePatchOrgDomainRequest {
	return &NullablePatchOrgDomainRequest{value: val, isSet: true}
}

func (v NullablePatchOrgDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchOrgDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


