/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.5
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the GetScannerMetrics200ResponseAlertsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetScannerMetrics200ResponseAlertsInner{}

// GetScannerMetrics200ResponseAlertsInner struct for GetScannerMetrics200ResponseAlertsInner
type GetScannerMetrics200ResponseAlertsInner struct {
	Chain *string `json:"chain,omitempty"`
	Lag *float32 `json:"lag,omitempty"`
	Threshold *float32 `json:"threshold,omitempty"`
}

// NewGetScannerMetrics200ResponseAlertsInner instantiates a new GetScannerMetrics200ResponseAlertsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetScannerMetrics200ResponseAlertsInner() *GetScannerMetrics200ResponseAlertsInner {
	this := GetScannerMetrics200ResponseAlertsInner{}
	return &this
}

// NewGetScannerMetrics200ResponseAlertsInnerWithDefaults instantiates a new GetScannerMetrics200ResponseAlertsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetScannerMetrics200ResponseAlertsInnerWithDefaults() *GetScannerMetrics200ResponseAlertsInner {
	this := GetScannerMetrics200ResponseAlertsInner{}
	return &this
}

// GetChain returns the Chain field value if set, zero value otherwise.
func (o *GetScannerMetrics200ResponseAlertsInner) GetChain() string {
	if o == nil || IsNil(o.Chain) {
		var ret string
		return ret
	}
	return *o.Chain
}

// GetChainOk returns a tuple with the Chain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetScannerMetrics200ResponseAlertsInner) GetChainOk() (*string, bool) {
	if o == nil || IsNil(o.Chain) {
		return nil, false
	}
	return o.Chain, true
}

// HasChain returns a boolean if a field has been set.
func (o *GetScannerMetrics200ResponseAlertsInner) HasChain() bool {
	if o != nil && !IsNil(o.Chain) {
		return true
	}

	return false
}

// SetChain gets a reference to the given string and assigns it to the Chain field.
func (o *GetScannerMetrics200ResponseAlertsInner) SetChain(v string) {
	o.Chain = &v
}

// GetLag returns the Lag field value if set, zero value otherwise.
func (o *GetScannerMetrics200ResponseAlertsInner) GetLag() float32 {
	if o == nil || IsNil(o.Lag) {
		var ret float32
		return ret
	}
	return *o.Lag
}

// GetLagOk returns a tuple with the Lag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetScannerMetrics200ResponseAlertsInner) GetLagOk() (*float32, bool) {
	if o == nil || IsNil(o.Lag) {
		return nil, false
	}
	return o.Lag, true
}

// HasLag returns a boolean if a field has been set.
func (o *GetScannerMetrics200ResponseAlertsInner) HasLag() bool {
	if o != nil && !IsNil(o.Lag) {
		return true
	}

	return false
}

// SetLag gets a reference to the given float32 and assigns it to the Lag field.
func (o *GetScannerMetrics200ResponseAlertsInner) SetLag(v float32) {
	o.Lag = &v
}

// GetThreshold returns the Threshold field value if set, zero value otherwise.
func (o *GetScannerMetrics200ResponseAlertsInner) GetThreshold() float32 {
	if o == nil || IsNil(o.Threshold) {
		var ret float32
		return ret
	}
	return *o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetScannerMetrics200ResponseAlertsInner) GetThresholdOk() (*float32, bool) {
	if o == nil || IsNil(o.Threshold) {
		return nil, false
	}
	return o.Threshold, true
}

// HasThreshold returns a boolean if a field has been set.
func (o *GetScannerMetrics200ResponseAlertsInner) HasThreshold() bool {
	if o != nil && !IsNil(o.Threshold) {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given float32 and assigns it to the Threshold field.
func (o *GetScannerMetrics200ResponseAlertsInner) SetThreshold(v float32) {
	o.Threshold = &v
}

func (o GetScannerMetrics200ResponseAlertsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetScannerMetrics200ResponseAlertsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Chain) {
		toSerialize["chain"] = o.Chain
	}
	if !IsNil(o.Lag) {
		toSerialize["lag"] = o.Lag
	}
	if !IsNil(o.Threshold) {
		toSerialize["threshold"] = o.Threshold
	}
	return toSerialize, nil
}

type NullableGetScannerMetrics200ResponseAlertsInner struct {
	value *GetScannerMetrics200ResponseAlertsInner
	isSet bool
}

func (v NullableGetScannerMetrics200ResponseAlertsInner) Get() *GetScannerMetrics200ResponseAlertsInner {
	return v.value
}

func (v *NullableGetScannerMetrics200ResponseAlertsInner) Set(val *GetScannerMetrics200ResponseAlertsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetScannerMetrics200ResponseAlertsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetScannerMetrics200ResponseAlertsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetScannerMetrics200ResponseAlertsInner(val *GetScannerMetrics200ResponseAlertsInner) *NullableGetScannerMetrics200ResponseAlertsInner {
	return &NullableGetScannerMetrics200ResponseAlertsInner{value: val, isSet: true}
}

func (v NullableGetScannerMetrics200ResponseAlertsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetScannerMetrics200ResponseAlertsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


