/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.1
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the Usage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Usage{}

// Usage Usage counts (projects, users, storage, bandwidth, apiCalls, dbReads, dbWrites).
type Usage struct {
	Projects *int32 `json:"projects,omitempty"`
	Users *int32 `json:"users,omitempty"`
	Storage *int32 `json:"storage,omitempty"`
	Bandwidth *int32 `json:"bandwidth,omitempty"`
	ApiCalls *int32 `json:"apiCalls,omitempty"`
	DbReads *int32 `json:"dbReads,omitempty"`
	DbWrites *int32 `json:"dbWrites,omitempty"`
}

// NewUsage instantiates a new Usage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsage() *Usage {
	this := Usage{}
	return &this
}

// NewUsageWithDefaults instantiates a new Usage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageWithDefaults() *Usage {
	this := Usage{}
	return &this
}

// GetProjects returns the Projects field value if set, zero value otherwise.
func (o *Usage) GetProjects() int32 {
	if o == nil || IsNil(o.Projects) {
		var ret int32
		return ret
	}
	return *o.Projects
}

// GetProjectsOk returns a tuple with the Projects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Usage) GetProjectsOk() (*int32, bool) {
	if o == nil || IsNil(o.Projects) {
		return nil, false
	}
	return o.Projects, true
}

// HasProjects returns a boolean if a field has been set.
func (o *Usage) HasProjects() bool {
	if o != nil && !IsNil(o.Projects) {
		return true
	}

	return false
}

// SetProjects gets a reference to the given int32 and assigns it to the Projects field.
func (o *Usage) SetProjects(v int32) {
	o.Projects = &v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *Usage) GetUsers() int32 {
	if o == nil || IsNil(o.Users) {
		var ret int32
		return ret
	}
	return *o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Usage) GetUsersOk() (*int32, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *Usage) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given int32 and assigns it to the Users field.
func (o *Usage) SetUsers(v int32) {
	o.Users = &v
}

// GetStorage returns the Storage field value if set, zero value otherwise.
func (o *Usage) GetStorage() int32 {
	if o == nil || IsNil(o.Storage) {
		var ret int32
		return ret
	}
	return *o.Storage
}

// GetStorageOk returns a tuple with the Storage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Usage) GetStorageOk() (*int32, bool) {
	if o == nil || IsNil(o.Storage) {
		return nil, false
	}
	return o.Storage, true
}

// HasStorage returns a boolean if a field has been set.
func (o *Usage) HasStorage() bool {
	if o != nil && !IsNil(o.Storage) {
		return true
	}

	return false
}

// SetStorage gets a reference to the given int32 and assigns it to the Storage field.
func (o *Usage) SetStorage(v int32) {
	o.Storage = &v
}

// GetBandwidth returns the Bandwidth field value if set, zero value otherwise.
func (o *Usage) GetBandwidth() int32 {
	if o == nil || IsNil(o.Bandwidth) {
		var ret int32
		return ret
	}
	return *o.Bandwidth
}

// GetBandwidthOk returns a tuple with the Bandwidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Usage) GetBandwidthOk() (*int32, bool) {
	if o == nil || IsNil(o.Bandwidth) {
		return nil, false
	}
	return o.Bandwidth, true
}

// HasBandwidth returns a boolean if a field has been set.
func (o *Usage) HasBandwidth() bool {
	if o != nil && !IsNil(o.Bandwidth) {
		return true
	}

	return false
}

// SetBandwidth gets a reference to the given int32 and assigns it to the Bandwidth field.
func (o *Usage) SetBandwidth(v int32) {
	o.Bandwidth = &v
}

// GetApiCalls returns the ApiCalls field value if set, zero value otherwise.
func (o *Usage) GetApiCalls() int32 {
	if o == nil || IsNil(o.ApiCalls) {
		var ret int32
		return ret
	}
	return *o.ApiCalls
}

// GetApiCallsOk returns a tuple with the ApiCalls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Usage) GetApiCallsOk() (*int32, bool) {
	if o == nil || IsNil(o.ApiCalls) {
		return nil, false
	}
	return o.ApiCalls, true
}

// HasApiCalls returns a boolean if a field has been set.
func (o *Usage) HasApiCalls() bool {
	if o != nil && !IsNil(o.ApiCalls) {
		return true
	}

	return false
}

// SetApiCalls gets a reference to the given int32 and assigns it to the ApiCalls field.
func (o *Usage) SetApiCalls(v int32) {
	o.ApiCalls = &v
}

// GetDbReads returns the DbReads field value if set, zero value otherwise.
func (o *Usage) GetDbReads() int32 {
	if o == nil || IsNil(o.DbReads) {
		var ret int32
		return ret
	}
	return *o.DbReads
}

// GetDbReadsOk returns a tuple with the DbReads field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Usage) GetDbReadsOk() (*int32, bool) {
	if o == nil || IsNil(o.DbReads) {
		return nil, false
	}
	return o.DbReads, true
}

// HasDbReads returns a boolean if a field has been set.
func (o *Usage) HasDbReads() bool {
	if o != nil && !IsNil(o.DbReads) {
		return true
	}

	return false
}

// SetDbReads gets a reference to the given int32 and assigns it to the DbReads field.
func (o *Usage) SetDbReads(v int32) {
	o.DbReads = &v
}

// GetDbWrites returns the DbWrites field value if set, zero value otherwise.
func (o *Usage) GetDbWrites() int32 {
	if o == nil || IsNil(o.DbWrites) {
		var ret int32
		return ret
	}
	return *o.DbWrites
}

// GetDbWritesOk returns a tuple with the DbWrites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Usage) GetDbWritesOk() (*int32, bool) {
	if o == nil || IsNil(o.DbWrites) {
		return nil, false
	}
	return o.DbWrites, true
}

// HasDbWrites returns a boolean if a field has been set.
func (o *Usage) HasDbWrites() bool {
	if o != nil && !IsNil(o.DbWrites) {
		return true
	}

	return false
}

// SetDbWrites gets a reference to the given int32 and assigns it to the DbWrites field.
func (o *Usage) SetDbWrites(v int32) {
	o.DbWrites = &v
}

func (o Usage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Usage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Projects) {
		toSerialize["projects"] = o.Projects
	}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	if !IsNil(o.Storage) {
		toSerialize["storage"] = o.Storage
	}
	if !IsNil(o.Bandwidth) {
		toSerialize["bandwidth"] = o.Bandwidth
	}
	if !IsNil(o.ApiCalls) {
		toSerialize["apiCalls"] = o.ApiCalls
	}
	if !IsNil(o.DbReads) {
		toSerialize["dbReads"] = o.DbReads
	}
	if !IsNil(o.DbWrites) {
		toSerialize["dbWrites"] = o.DbWrites
	}
	return toSerialize, nil
}

type NullableUsage struct {
	value *Usage
	isSet bool
}

func (v NullableUsage) Get() *Usage {
	return v.value
}

func (v *NullableUsage) Set(val *Usage) {
	v.value = val
	v.isSet = true
}

func (v NullableUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsage(val *Usage) *NullableUsage {
	return &NullableUsage{value: val, isSet: true}
}

func (v NullableUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


