/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.8
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the UsersEraseData200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersEraseData200Response{}

// UsersEraseData200Response struct for UsersEraseData200Response
type UsersEraseData200Response struct {
	Message *string `json:"message,omitempty"`
	Details *UsersEraseData200ResponseDetails `json:"details,omitempty"`
}

// NewUsersEraseData200Response instantiates a new UsersEraseData200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersEraseData200Response() *UsersEraseData200Response {
	this := UsersEraseData200Response{}
	return &this
}

// NewUsersEraseData200ResponseWithDefaults instantiates a new UsersEraseData200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersEraseData200ResponseWithDefaults() *UsersEraseData200Response {
	this := UsersEraseData200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UsersEraseData200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersEraseData200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UsersEraseData200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UsersEraseData200Response) SetMessage(v string) {
	o.Message = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *UsersEraseData200Response) GetDetails() UsersEraseData200ResponseDetails {
	if o == nil || IsNil(o.Details) {
		var ret UsersEraseData200ResponseDetails
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersEraseData200Response) GetDetailsOk() (*UsersEraseData200ResponseDetails, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *UsersEraseData200Response) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given UsersEraseData200ResponseDetails and assigns it to the Details field.
func (o *UsersEraseData200Response) SetDetails(v UsersEraseData200ResponseDetails) {
	o.Details = &v
}

func (o UsersEraseData200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersEraseData200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	return toSerialize, nil
}

type NullableUsersEraseData200Response struct {
	value *UsersEraseData200Response
	isSet bool
}

func (v NullableUsersEraseData200Response) Get() *UsersEraseData200Response {
	return v.value
}

func (v *NullableUsersEraseData200Response) Set(val *UsersEraseData200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersEraseData200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersEraseData200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersEraseData200Response(val *UsersEraseData200Response) *NullableUsersEraseData200Response {
	return &NullableUsersEraseData200Response{value: val, isSet: true}
}

func (v NullableUsersEraseData200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersEraseData200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


