/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.2
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
	"time"
)

// checks if the ChatGetMessages200ResponseDataMessagesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatGetMessages200ResponseDataMessagesInner{}

// ChatGetMessages200ResponseDataMessagesInner struct for ChatGetMessages200ResponseDataMessagesInner
type ChatGetMessages200ResponseDataMessagesInner struct {
	Id *string `json:"_id,omitempty"`
	Content *string `json:"content,omitempty"`
	Sender *ChatGetMessages200ResponseDataMessagesInnerSender `json:"sender,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
}

// NewChatGetMessages200ResponseDataMessagesInner instantiates a new ChatGetMessages200ResponseDataMessagesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatGetMessages200ResponseDataMessagesInner() *ChatGetMessages200ResponseDataMessagesInner {
	this := ChatGetMessages200ResponseDataMessagesInner{}
	return &this
}

// NewChatGetMessages200ResponseDataMessagesInnerWithDefaults instantiates a new ChatGetMessages200ResponseDataMessagesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatGetMessages200ResponseDataMessagesInnerWithDefaults() *ChatGetMessages200ResponseDataMessagesInner {
	this := ChatGetMessages200ResponseDataMessagesInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ChatGetMessages200ResponseDataMessagesInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatGetMessages200ResponseDataMessagesInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ChatGetMessages200ResponseDataMessagesInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ChatGetMessages200ResponseDataMessagesInner) SetId(v string) {
	o.Id = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *ChatGetMessages200ResponseDataMessagesInner) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatGetMessages200ResponseDataMessagesInner) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *ChatGetMessages200ResponseDataMessagesInner) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *ChatGetMessages200ResponseDataMessagesInner) SetContent(v string) {
	o.Content = &v
}

// GetSender returns the Sender field value if set, zero value otherwise.
func (o *ChatGetMessages200ResponseDataMessagesInner) GetSender() ChatGetMessages200ResponseDataMessagesInnerSender {
	if o == nil || IsNil(o.Sender) {
		var ret ChatGetMessages200ResponseDataMessagesInnerSender
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatGetMessages200ResponseDataMessagesInner) GetSenderOk() (*ChatGetMessages200ResponseDataMessagesInnerSender, bool) {
	if o == nil || IsNil(o.Sender) {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *ChatGetMessages200ResponseDataMessagesInner) HasSender() bool {
	if o != nil && !IsNil(o.Sender) {
		return true
	}

	return false
}

// SetSender gets a reference to the given ChatGetMessages200ResponseDataMessagesInnerSender and assigns it to the Sender field.
func (o *ChatGetMessages200ResponseDataMessagesInner) SetSender(v ChatGetMessages200ResponseDataMessagesInnerSender) {
	o.Sender = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ChatGetMessages200ResponseDataMessagesInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatGetMessages200ResponseDataMessagesInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ChatGetMessages200ResponseDataMessagesInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ChatGetMessages200ResponseDataMessagesInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o ChatGetMessages200ResponseDataMessagesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatGetMessages200ResponseDataMessagesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["_id"] = o.Id
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Sender) {
		toSerialize["sender"] = o.Sender
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableChatGetMessages200ResponseDataMessagesInner struct {
	value *ChatGetMessages200ResponseDataMessagesInner
	isSet bool
}

func (v NullableChatGetMessages200ResponseDataMessagesInner) Get() *ChatGetMessages200ResponseDataMessagesInner {
	return v.value
}

func (v *NullableChatGetMessages200ResponseDataMessagesInner) Set(val *ChatGetMessages200ResponseDataMessagesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableChatGetMessages200ResponseDataMessagesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableChatGetMessages200ResponseDataMessagesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatGetMessages200ResponseDataMessagesInner(val *ChatGetMessages200ResponseDataMessagesInner) *NullableChatGetMessages200ResponseDataMessagesInner {
	return &NullableChatGetMessages200ResponseDataMessagesInner{value: val, isSet: true}
}

func (v NullableChatGetMessages200ResponseDataMessagesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatGetMessages200ResponseDataMessagesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


