/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.7
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the SystemStatusResponseDataCpu type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemStatusResponseDataCpu{}

// SystemStatusResponseDataCpu struct for SystemStatusResponseDataCpu
type SystemStatusResponseDataCpu struct {
	Usage *float32 `json:"usage,omitempty"`
	Cores *int32 `json:"cores,omitempty"`
}

// NewSystemStatusResponseDataCpu instantiates a new SystemStatusResponseDataCpu object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemStatusResponseDataCpu() *SystemStatusResponseDataCpu {
	this := SystemStatusResponseDataCpu{}
	return &this
}

// NewSystemStatusResponseDataCpuWithDefaults instantiates a new SystemStatusResponseDataCpu object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemStatusResponseDataCpuWithDefaults() *SystemStatusResponseDataCpu {
	this := SystemStatusResponseDataCpu{}
	return &this
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *SystemStatusResponseDataCpu) GetUsage() float32 {
	if o == nil || IsNil(o.Usage) {
		var ret float32
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatusResponseDataCpu) GetUsageOk() (*float32, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *SystemStatusResponseDataCpu) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given float32 and assigns it to the Usage field.
func (o *SystemStatusResponseDataCpu) SetUsage(v float32) {
	o.Usage = &v
}

// GetCores returns the Cores field value if set, zero value otherwise.
func (o *SystemStatusResponseDataCpu) GetCores() int32 {
	if o == nil || IsNil(o.Cores) {
		var ret int32
		return ret
	}
	return *o.Cores
}

// GetCoresOk returns a tuple with the Cores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStatusResponseDataCpu) GetCoresOk() (*int32, bool) {
	if o == nil || IsNil(o.Cores) {
		return nil, false
	}
	return o.Cores, true
}

// HasCores returns a boolean if a field has been set.
func (o *SystemStatusResponseDataCpu) HasCores() bool {
	if o != nil && !IsNil(o.Cores) {
		return true
	}

	return false
}

// SetCores gets a reference to the given int32 and assigns it to the Cores field.
func (o *SystemStatusResponseDataCpu) SetCores(v int32) {
	o.Cores = &v
}

func (o SystemStatusResponseDataCpu) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemStatusResponseDataCpu) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	if !IsNil(o.Cores) {
		toSerialize["cores"] = o.Cores
	}
	return toSerialize, nil
}

type NullableSystemStatusResponseDataCpu struct {
	value *SystemStatusResponseDataCpu
	isSet bool
}

func (v NullableSystemStatusResponseDataCpu) Get() *SystemStatusResponseDataCpu {
	return v.value
}

func (v *NullableSystemStatusResponseDataCpu) Set(val *SystemStatusResponseDataCpu) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemStatusResponseDataCpu) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemStatusResponseDataCpu) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemStatusResponseDataCpu(val *SystemStatusResponseDataCpu) *NullableSystemStatusResponseDataCpu {
	return &NullableSystemStatusResponseDataCpu{value: val, isSet: true}
}

func (v NullableSystemStatusResponseDataCpu) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemStatusResponseDataCpu) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


