/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.3
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestManualPayoutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestManualPayoutRequest{}

// RequestManualPayoutRequest struct for RequestManualPayoutRequest
type RequestManualPayoutRequest struct {
	Currency string `json:"currency"`
}

type _RequestManualPayoutRequest RequestManualPayoutRequest

// NewRequestManualPayoutRequest instantiates a new RequestManualPayoutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestManualPayoutRequest(currency string) *RequestManualPayoutRequest {
	this := RequestManualPayoutRequest{}
	this.Currency = currency
	return &this
}

// NewRequestManualPayoutRequestWithDefaults instantiates a new RequestManualPayoutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestManualPayoutRequestWithDefaults() *RequestManualPayoutRequest {
	this := RequestManualPayoutRequest{}
	return &this
}

// GetCurrency returns the Currency field value
func (o *RequestManualPayoutRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *RequestManualPayoutRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *RequestManualPayoutRequest) SetCurrency(v string) {
	o.Currency = v
}

func (o RequestManualPayoutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestManualPayoutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["currency"] = o.Currency
	return toSerialize, nil
}

func (o *RequestManualPayoutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestManualPayoutRequest := _RequestManualPayoutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestManualPayoutRequest)

	if err != nil {
		return err
	}

	*o = RequestManualPayoutRequest(varRequestManualPayoutRequest)

	return err
}

type NullableRequestManualPayoutRequest struct {
	value *RequestManualPayoutRequest
	isSet bool
}

func (v NullableRequestManualPayoutRequest) Get() *RequestManualPayoutRequest {
	return v.value
}

func (v *NullableRequestManualPayoutRequest) Set(val *RequestManualPayoutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestManualPayoutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestManualPayoutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestManualPayoutRequest(val *RequestManualPayoutRequest) *NullableRequestManualPayoutRequest {
	return &NullableRequestManualPayoutRequest{value: val, isSet: true}
}

func (v NullableRequestManualPayoutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestManualPayoutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


