/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.9
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdminCustomDomainMutationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminCustomDomainMutationResponse{}

// AdminCustomDomainMutationResponse struct for AdminCustomDomainMutationResponse
type AdminCustomDomainMutationResponse struct {
	Success bool `json:"success"`
	Domain OrgDomainEntryWithDns `json:"domain"`
}

type _AdminCustomDomainMutationResponse AdminCustomDomainMutationResponse

// NewAdminCustomDomainMutationResponse instantiates a new AdminCustomDomainMutationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminCustomDomainMutationResponse(success bool, domain OrgDomainEntryWithDns) *AdminCustomDomainMutationResponse {
	this := AdminCustomDomainMutationResponse{}
	this.Success = success
	this.Domain = domain
	return &this
}

// NewAdminCustomDomainMutationResponseWithDefaults instantiates a new AdminCustomDomainMutationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminCustomDomainMutationResponseWithDefaults() *AdminCustomDomainMutationResponse {
	this := AdminCustomDomainMutationResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *AdminCustomDomainMutationResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *AdminCustomDomainMutationResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *AdminCustomDomainMutationResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetDomain returns the Domain field value
func (o *AdminCustomDomainMutationResponse) GetDomain() OrgDomainEntryWithDns {
	if o == nil {
		var ret OrgDomainEntryWithDns
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *AdminCustomDomainMutationResponse) GetDomainOk() (*OrgDomainEntryWithDns, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *AdminCustomDomainMutationResponse) SetDomain(v OrgDomainEntryWithDns) {
	o.Domain = v
}

func (o AdminCustomDomainMutationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminCustomDomainMutationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["domain"] = o.Domain
	return toSerialize, nil
}

func (o *AdminCustomDomainMutationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"domain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminCustomDomainMutationResponse := _AdminCustomDomainMutationResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdminCustomDomainMutationResponse)

	if err != nil {
		return err
	}

	*o = AdminCustomDomainMutationResponse(varAdminCustomDomainMutationResponse)

	return err
}

type NullableAdminCustomDomainMutationResponse struct {
	value *AdminCustomDomainMutationResponse
	isSet bool
}

func (v NullableAdminCustomDomainMutationResponse) Get() *AdminCustomDomainMutationResponse {
	return v.value
}

func (v *NullableAdminCustomDomainMutationResponse) Set(val *AdminCustomDomainMutationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminCustomDomainMutationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminCustomDomainMutationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminCustomDomainMutationResponse(val *AdminCustomDomainMutationResponse) *NullableAdminCustomDomainMutationResponse {
	return &NullableAdminCustomDomainMutationResponse{value: val, isSet: true}
}

func (v NullableAdminCustomDomainMutationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminCustomDomainMutationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


