/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise: custom domains under `GET/POST/PATCH/DELETE /api/orgs/{orgId}/projects/{projectId}/domains` (plan `features.customDomainAllowed`); stable error codes `hostname_in_use`, `domain_limit_reached`, `domain_rate_limited`, `custom_domain_not_allowed`, `provision_conflict`, `not_enterprise_plan`; internal `POST /internal/provision-enterprise` with header `X-Internal-Api-Key`; responses on platform host may include `X-Mudbase-Warning: use_dedicated_api` for dedicated orgs. 

API version: 1.2.10
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the OrganizationsPatchDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsPatchDomainRequest{}

// OrganizationsPatchDomainRequest struct for OrganizationsPatchDomainRequest
type OrganizationsPatchDomainRequest struct {
	// Org self-serve only pending or failed. Live (active) is set by platform admin.
	Status *string `json:"status,omitempty"`
	RegenerateToken *bool `json:"regenerateToken,omitempty"`
}

// NewOrganizationsPatchDomainRequest instantiates a new OrganizationsPatchDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsPatchDomainRequest() *OrganizationsPatchDomainRequest {
	this := OrganizationsPatchDomainRequest{}
	return &this
}

// NewOrganizationsPatchDomainRequestWithDefaults instantiates a new OrganizationsPatchDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsPatchDomainRequestWithDefaults() *OrganizationsPatchDomainRequest {
	this := OrganizationsPatchDomainRequest{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *OrganizationsPatchDomainRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsPatchDomainRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *OrganizationsPatchDomainRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *OrganizationsPatchDomainRequest) SetStatus(v string) {
	o.Status = &v
}

// GetRegenerateToken returns the RegenerateToken field value if set, zero value otherwise.
func (o *OrganizationsPatchDomainRequest) GetRegenerateToken() bool {
	if o == nil || IsNil(o.RegenerateToken) {
		var ret bool
		return ret
	}
	return *o.RegenerateToken
}

// GetRegenerateTokenOk returns a tuple with the RegenerateToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsPatchDomainRequest) GetRegenerateTokenOk() (*bool, bool) {
	if o == nil || IsNil(o.RegenerateToken) {
		return nil, false
	}
	return o.RegenerateToken, true
}

// HasRegenerateToken returns a boolean if a field has been set.
func (o *OrganizationsPatchDomainRequest) HasRegenerateToken() bool {
	if o != nil && !IsNil(o.RegenerateToken) {
		return true
	}

	return false
}

// SetRegenerateToken gets a reference to the given bool and assigns it to the RegenerateToken field.
func (o *OrganizationsPatchDomainRequest) SetRegenerateToken(v bool) {
	o.RegenerateToken = &v
}

func (o OrganizationsPatchDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsPatchDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.RegenerateToken) {
		toSerialize["regenerateToken"] = o.RegenerateToken
	}
	return toSerialize, nil
}

type NullableOrganizationsPatchDomainRequest struct {
	value *OrganizationsPatchDomainRequest
	isSet bool
}

func (v NullableOrganizationsPatchDomainRequest) Get() *OrganizationsPatchDomainRequest {
	return v.value
}

func (v *NullableOrganizationsPatchDomainRequest) Set(val *OrganizationsPatchDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsPatchDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsPatchDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsPatchDomainRequest(val *OrganizationsPatchDomainRequest) *NullableOrganizationsPatchDomainRequest {
	return &NullableOrganizationsPatchDomainRequest{value: val, isSet: true}
}

func (v NullableOrganizationsPatchDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsPatchDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


