/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.4
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the ApiMeBootstrapGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMeBootstrapGet200Response{}

// ApiMeBootstrapGet200Response struct for ApiMeBootstrapGet200Response
type ApiMeBootstrapGet200Response struct {
	User map[string]interface{} `json:"user,omitempty"`
	Organizations []map[string]interface{} `json:"organizations,omitempty"`
	DefaultOrg map[string]interface{} `json:"defaultOrg,omitempty"`
	Projects []map[string]interface{} `json:"projects,omitempty"`
}

// NewApiMeBootstrapGet200Response instantiates a new ApiMeBootstrapGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMeBootstrapGet200Response() *ApiMeBootstrapGet200Response {
	this := ApiMeBootstrapGet200Response{}
	return &this
}

// NewApiMeBootstrapGet200ResponseWithDefaults instantiates a new ApiMeBootstrapGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMeBootstrapGet200ResponseWithDefaults() *ApiMeBootstrapGet200Response {
	this := ApiMeBootstrapGet200Response{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *ApiMeBootstrapGet200Response) GetUser() map[string]interface{} {
	if o == nil || IsNil(o.User) {
		var ret map[string]interface{}
		return ret
	}
	return o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMeBootstrapGet200Response) GetUserOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.User) {
		return map[string]interface{}{}, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *ApiMeBootstrapGet200Response) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given map[string]interface{} and assigns it to the User field.
func (o *ApiMeBootstrapGet200Response) SetUser(v map[string]interface{}) {
	o.User = v
}

// GetOrganizations returns the Organizations field value if set, zero value otherwise.
func (o *ApiMeBootstrapGet200Response) GetOrganizations() []map[string]interface{} {
	if o == nil || IsNil(o.Organizations) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Organizations
}

// GetOrganizationsOk returns a tuple with the Organizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMeBootstrapGet200Response) GetOrganizationsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Organizations) {
		return nil, false
	}
	return o.Organizations, true
}

// HasOrganizations returns a boolean if a field has been set.
func (o *ApiMeBootstrapGet200Response) HasOrganizations() bool {
	if o != nil && !IsNil(o.Organizations) {
		return true
	}

	return false
}

// SetOrganizations gets a reference to the given []map[string]interface{} and assigns it to the Organizations field.
func (o *ApiMeBootstrapGet200Response) SetOrganizations(v []map[string]interface{}) {
	o.Organizations = v
}

// GetDefaultOrg returns the DefaultOrg field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiMeBootstrapGet200Response) GetDefaultOrg() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.DefaultOrg
}

// GetDefaultOrgOk returns a tuple with the DefaultOrg field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiMeBootstrapGet200Response) GetDefaultOrgOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.DefaultOrg) {
		return map[string]interface{}{}, false
	}
	return o.DefaultOrg, true
}

// HasDefaultOrg returns a boolean if a field has been set.
func (o *ApiMeBootstrapGet200Response) HasDefaultOrg() bool {
	if o != nil && !IsNil(o.DefaultOrg) {
		return true
	}

	return false
}

// SetDefaultOrg gets a reference to the given map[string]interface{} and assigns it to the DefaultOrg field.
func (o *ApiMeBootstrapGet200Response) SetDefaultOrg(v map[string]interface{}) {
	o.DefaultOrg = v
}

// GetProjects returns the Projects field value if set, zero value otherwise.
func (o *ApiMeBootstrapGet200Response) GetProjects() []map[string]interface{} {
	if o == nil || IsNil(o.Projects) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Projects
}

// GetProjectsOk returns a tuple with the Projects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMeBootstrapGet200Response) GetProjectsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Projects) {
		return nil, false
	}
	return o.Projects, true
}

// HasProjects returns a boolean if a field has been set.
func (o *ApiMeBootstrapGet200Response) HasProjects() bool {
	if o != nil && !IsNil(o.Projects) {
		return true
	}

	return false
}

// SetProjects gets a reference to the given []map[string]interface{} and assigns it to the Projects field.
func (o *ApiMeBootstrapGet200Response) SetProjects(v []map[string]interface{}) {
	o.Projects = v
}

func (o ApiMeBootstrapGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMeBootstrapGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Organizations) {
		toSerialize["organizations"] = o.Organizations
	}
	if o.DefaultOrg != nil {
		toSerialize["defaultOrg"] = o.DefaultOrg
	}
	if !IsNil(o.Projects) {
		toSerialize["projects"] = o.Projects
	}
	return toSerialize, nil
}

type NullableApiMeBootstrapGet200Response struct {
	value *ApiMeBootstrapGet200Response
	isSet bool
}

func (v NullableApiMeBootstrapGet200Response) Get() *ApiMeBootstrapGet200Response {
	return v.value
}

func (v *NullableApiMeBootstrapGet200Response) Set(val *ApiMeBootstrapGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMeBootstrapGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMeBootstrapGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMeBootstrapGet200Response(val *ApiMeBootstrapGet200Response) *NullableApiMeBootstrapGet200Response {
	return &NullableApiMeBootstrapGet200Response{value: val, isSet: true}
}

func (v NullableApiMeBootstrapGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMeBootstrapGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


