/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.4
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the GetNetworkStatus200ResponseDataValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkStatus200ResponseDataValue{}

// GetNetworkStatus200ResponseDataValue struct for GetNetworkStatus200ResponseDataValue
type GetNetworkStatus200ResponseDataValue struct {
	Congestion *string `json:"congestion,omitempty"`
	// EVM only
	GasPriceGwei *float32 `json:"gasPriceGwei,omitempty"`
	// UTXO only
	SatPerVb *float32 `json:"satPerVb,omitempty"`
	NetworkFee *string `json:"networkFee,omitempty"`
}

// NewGetNetworkStatus200ResponseDataValue instantiates a new GetNetworkStatus200ResponseDataValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkStatus200ResponseDataValue() *GetNetworkStatus200ResponseDataValue {
	this := GetNetworkStatus200ResponseDataValue{}
	return &this
}

// NewGetNetworkStatus200ResponseDataValueWithDefaults instantiates a new GetNetworkStatus200ResponseDataValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkStatus200ResponseDataValueWithDefaults() *GetNetworkStatus200ResponseDataValue {
	this := GetNetworkStatus200ResponseDataValue{}
	return &this
}

// GetCongestion returns the Congestion field value if set, zero value otherwise.
func (o *GetNetworkStatus200ResponseDataValue) GetCongestion() string {
	if o == nil || IsNil(o.Congestion) {
		var ret string
		return ret
	}
	return *o.Congestion
}

// GetCongestionOk returns a tuple with the Congestion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkStatus200ResponseDataValue) GetCongestionOk() (*string, bool) {
	if o == nil || IsNil(o.Congestion) {
		return nil, false
	}
	return o.Congestion, true
}

// HasCongestion returns a boolean if a field has been set.
func (o *GetNetworkStatus200ResponseDataValue) HasCongestion() bool {
	if o != nil && !IsNil(o.Congestion) {
		return true
	}

	return false
}

// SetCongestion gets a reference to the given string and assigns it to the Congestion field.
func (o *GetNetworkStatus200ResponseDataValue) SetCongestion(v string) {
	o.Congestion = &v
}

// GetGasPriceGwei returns the GasPriceGwei field value if set, zero value otherwise.
func (o *GetNetworkStatus200ResponseDataValue) GetGasPriceGwei() float32 {
	if o == nil || IsNil(o.GasPriceGwei) {
		var ret float32
		return ret
	}
	return *o.GasPriceGwei
}

// GetGasPriceGweiOk returns a tuple with the GasPriceGwei field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkStatus200ResponseDataValue) GetGasPriceGweiOk() (*float32, bool) {
	if o == nil || IsNil(o.GasPriceGwei) {
		return nil, false
	}
	return o.GasPriceGwei, true
}

// HasGasPriceGwei returns a boolean if a field has been set.
func (o *GetNetworkStatus200ResponseDataValue) HasGasPriceGwei() bool {
	if o != nil && !IsNil(o.GasPriceGwei) {
		return true
	}

	return false
}

// SetGasPriceGwei gets a reference to the given float32 and assigns it to the GasPriceGwei field.
func (o *GetNetworkStatus200ResponseDataValue) SetGasPriceGwei(v float32) {
	o.GasPriceGwei = &v
}

// GetSatPerVb returns the SatPerVb field value if set, zero value otherwise.
func (o *GetNetworkStatus200ResponseDataValue) GetSatPerVb() float32 {
	if o == nil || IsNil(o.SatPerVb) {
		var ret float32
		return ret
	}
	return *o.SatPerVb
}

// GetSatPerVbOk returns a tuple with the SatPerVb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkStatus200ResponseDataValue) GetSatPerVbOk() (*float32, bool) {
	if o == nil || IsNil(o.SatPerVb) {
		return nil, false
	}
	return o.SatPerVb, true
}

// HasSatPerVb returns a boolean if a field has been set.
func (o *GetNetworkStatus200ResponseDataValue) HasSatPerVb() bool {
	if o != nil && !IsNil(o.SatPerVb) {
		return true
	}

	return false
}

// SetSatPerVb gets a reference to the given float32 and assigns it to the SatPerVb field.
func (o *GetNetworkStatus200ResponseDataValue) SetSatPerVb(v float32) {
	o.SatPerVb = &v
}

// GetNetworkFee returns the NetworkFee field value if set, zero value otherwise.
func (o *GetNetworkStatus200ResponseDataValue) GetNetworkFee() string {
	if o == nil || IsNil(o.NetworkFee) {
		var ret string
		return ret
	}
	return *o.NetworkFee
}

// GetNetworkFeeOk returns a tuple with the NetworkFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkStatus200ResponseDataValue) GetNetworkFeeOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkFee) {
		return nil, false
	}
	return o.NetworkFee, true
}

// HasNetworkFee returns a boolean if a field has been set.
func (o *GetNetworkStatus200ResponseDataValue) HasNetworkFee() bool {
	if o != nil && !IsNil(o.NetworkFee) {
		return true
	}

	return false
}

// SetNetworkFee gets a reference to the given string and assigns it to the NetworkFee field.
func (o *GetNetworkStatus200ResponseDataValue) SetNetworkFee(v string) {
	o.NetworkFee = &v
}

func (o GetNetworkStatus200ResponseDataValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkStatus200ResponseDataValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Congestion) {
		toSerialize["congestion"] = o.Congestion
	}
	if !IsNil(o.GasPriceGwei) {
		toSerialize["gasPriceGwei"] = o.GasPriceGwei
	}
	if !IsNil(o.SatPerVb) {
		toSerialize["satPerVb"] = o.SatPerVb
	}
	if !IsNil(o.NetworkFee) {
		toSerialize["networkFee"] = o.NetworkFee
	}
	return toSerialize, nil
}

type NullableGetNetworkStatus200ResponseDataValue struct {
	value *GetNetworkStatus200ResponseDataValue
	isSet bool
}

func (v NullableGetNetworkStatus200ResponseDataValue) Get() *GetNetworkStatus200ResponseDataValue {
	return v.value
}

func (v *NullableGetNetworkStatus200ResponseDataValue) Set(val *GetNetworkStatus200ResponseDataValue) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkStatus200ResponseDataValue) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkStatus200ResponseDataValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkStatus200ResponseDataValue(val *GetNetworkStatus200ResponseDataValue) *NullableGetNetworkStatus200ResponseDataValue {
	return &NullableGetNetworkStatus200ResponseDataValue{value: val, isSet: true}
}

func (v NullableGetNetworkStatus200ResponseDataValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkStatus200ResponseDataValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


