/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) 

API version: 1.2.5
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mudbase

import (
	"encoding/json"
)

// checks if the MessageStatsResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageStatsResponseData{}

// MessageStatsResponseData struct for MessageStatsResponseData
type MessageStatsResponseData struct {
	TotalMessages *int32 `json:"totalMessages,omitempty"`
	ByType *MessageStatsResponseDataByType `json:"byType,omitempty"`
	ByStatus *MessageStatsResponseDataByStatus `json:"byStatus,omitempty"`
	SuccessRate *float32 `json:"successRate,omitempty"`
	Period *MessageStatsResponseDataPeriod `json:"period,omitempty"`
}

// NewMessageStatsResponseData instantiates a new MessageStatsResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageStatsResponseData() *MessageStatsResponseData {
	this := MessageStatsResponseData{}
	return &this
}

// NewMessageStatsResponseDataWithDefaults instantiates a new MessageStatsResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageStatsResponseDataWithDefaults() *MessageStatsResponseData {
	this := MessageStatsResponseData{}
	return &this
}

// GetTotalMessages returns the TotalMessages field value if set, zero value otherwise.
func (o *MessageStatsResponseData) GetTotalMessages() int32 {
	if o == nil || IsNil(o.TotalMessages) {
		var ret int32
		return ret
	}
	return *o.TotalMessages
}

// GetTotalMessagesOk returns a tuple with the TotalMessages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageStatsResponseData) GetTotalMessagesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalMessages) {
		return nil, false
	}
	return o.TotalMessages, true
}

// HasTotalMessages returns a boolean if a field has been set.
func (o *MessageStatsResponseData) HasTotalMessages() bool {
	if o != nil && !IsNil(o.TotalMessages) {
		return true
	}

	return false
}

// SetTotalMessages gets a reference to the given int32 and assigns it to the TotalMessages field.
func (o *MessageStatsResponseData) SetTotalMessages(v int32) {
	o.TotalMessages = &v
}

// GetByType returns the ByType field value if set, zero value otherwise.
func (o *MessageStatsResponseData) GetByType() MessageStatsResponseDataByType {
	if o == nil || IsNil(o.ByType) {
		var ret MessageStatsResponseDataByType
		return ret
	}
	return *o.ByType
}

// GetByTypeOk returns a tuple with the ByType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageStatsResponseData) GetByTypeOk() (*MessageStatsResponseDataByType, bool) {
	if o == nil || IsNil(o.ByType) {
		return nil, false
	}
	return o.ByType, true
}

// HasByType returns a boolean if a field has been set.
func (o *MessageStatsResponseData) HasByType() bool {
	if o != nil && !IsNil(o.ByType) {
		return true
	}

	return false
}

// SetByType gets a reference to the given MessageStatsResponseDataByType and assigns it to the ByType field.
func (o *MessageStatsResponseData) SetByType(v MessageStatsResponseDataByType) {
	o.ByType = &v
}

// GetByStatus returns the ByStatus field value if set, zero value otherwise.
func (o *MessageStatsResponseData) GetByStatus() MessageStatsResponseDataByStatus {
	if o == nil || IsNil(o.ByStatus) {
		var ret MessageStatsResponseDataByStatus
		return ret
	}
	return *o.ByStatus
}

// GetByStatusOk returns a tuple with the ByStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageStatsResponseData) GetByStatusOk() (*MessageStatsResponseDataByStatus, bool) {
	if o == nil || IsNil(o.ByStatus) {
		return nil, false
	}
	return o.ByStatus, true
}

// HasByStatus returns a boolean if a field has been set.
func (o *MessageStatsResponseData) HasByStatus() bool {
	if o != nil && !IsNil(o.ByStatus) {
		return true
	}

	return false
}

// SetByStatus gets a reference to the given MessageStatsResponseDataByStatus and assigns it to the ByStatus field.
func (o *MessageStatsResponseData) SetByStatus(v MessageStatsResponseDataByStatus) {
	o.ByStatus = &v
}

// GetSuccessRate returns the SuccessRate field value if set, zero value otherwise.
func (o *MessageStatsResponseData) GetSuccessRate() float32 {
	if o == nil || IsNil(o.SuccessRate) {
		var ret float32
		return ret
	}
	return *o.SuccessRate
}

// GetSuccessRateOk returns a tuple with the SuccessRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageStatsResponseData) GetSuccessRateOk() (*float32, bool) {
	if o == nil || IsNil(o.SuccessRate) {
		return nil, false
	}
	return o.SuccessRate, true
}

// HasSuccessRate returns a boolean if a field has been set.
func (o *MessageStatsResponseData) HasSuccessRate() bool {
	if o != nil && !IsNil(o.SuccessRate) {
		return true
	}

	return false
}

// SetSuccessRate gets a reference to the given float32 and assigns it to the SuccessRate field.
func (o *MessageStatsResponseData) SetSuccessRate(v float32) {
	o.SuccessRate = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *MessageStatsResponseData) GetPeriod() MessageStatsResponseDataPeriod {
	if o == nil || IsNil(o.Period) {
		var ret MessageStatsResponseDataPeriod
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageStatsResponseData) GetPeriodOk() (*MessageStatsResponseDataPeriod, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *MessageStatsResponseData) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given MessageStatsResponseDataPeriod and assigns it to the Period field.
func (o *MessageStatsResponseData) SetPeriod(v MessageStatsResponseDataPeriod) {
	o.Period = &v
}

func (o MessageStatsResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageStatsResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalMessages) {
		toSerialize["totalMessages"] = o.TotalMessages
	}
	if !IsNil(o.ByType) {
		toSerialize["byType"] = o.ByType
	}
	if !IsNil(o.ByStatus) {
		toSerialize["byStatus"] = o.ByStatus
	}
	if !IsNil(o.SuccessRate) {
		toSerialize["successRate"] = o.SuccessRate
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	return toSerialize, nil
}

type NullableMessageStatsResponseData struct {
	value *MessageStatsResponseData
	isSet bool
}

func (v NullableMessageStatsResponseData) Get() *MessageStatsResponseData {
	return v.value
}

func (v *NullableMessageStatsResponseData) Set(val *MessageStatsResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageStatsResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageStatsResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageStatsResponseData(val *MessageStatsResponseData) *NullableMessageStatsResponseData {
	return &NullableMessageStatsResponseData{value: val, isSet: true}
}

func (v NullableMessageStatsResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageStatsResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


