/*
MUDBASESDK

MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

API version: 1.3.17
Contact: support@mudbase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the GetPayoutCountries200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPayoutCountries200ResponseData{}

// GetPayoutCountries200ResponseData struct for GetPayoutCountries200ResponseData
type GetPayoutCountries200ResponseData struct {
	Countries []GetPayoutCountries200ResponseDataCountriesInner `json:"countries,omitempty"`
}

// NewGetPayoutCountries200ResponseData instantiates a new GetPayoutCountries200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPayoutCountries200ResponseData() *GetPayoutCountries200ResponseData {
	this := GetPayoutCountries200ResponseData{}
	return &this
}

// NewGetPayoutCountries200ResponseDataWithDefaults instantiates a new GetPayoutCountries200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPayoutCountries200ResponseDataWithDefaults() *GetPayoutCountries200ResponseData {
	this := GetPayoutCountries200ResponseData{}
	return &this
}

// GetCountries returns the Countries field value if set, zero value otherwise.
func (o *GetPayoutCountries200ResponseData) GetCountries() []GetPayoutCountries200ResponseDataCountriesInner {
	if o == nil || IsNil(o.Countries) {
		var ret []GetPayoutCountries200ResponseDataCountriesInner
		return ret
	}
	return o.Countries
}

// GetCountriesOk returns a tuple with the Countries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPayoutCountries200ResponseData) GetCountriesOk() ([]GetPayoutCountries200ResponseDataCountriesInner, bool) {
	if o == nil || IsNil(o.Countries) {
		return nil, false
	}
	return o.Countries, true
}

// HasCountries returns a boolean if a field has been set.
func (o *GetPayoutCountries200ResponseData) HasCountries() bool {
	if o != nil && !IsNil(o.Countries) {
		return true
	}

	return false
}

// SetCountries gets a reference to the given []GetPayoutCountries200ResponseDataCountriesInner and assigns it to the Countries field.
func (o *GetPayoutCountries200ResponseData) SetCountries(v []GetPayoutCountries200ResponseDataCountriesInner) {
	o.Countries = v
}

func (o GetPayoutCountries200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPayoutCountries200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Countries) {
		toSerialize["countries"] = o.Countries
	}
	return toSerialize, nil
}

type NullableGetPayoutCountries200ResponseData struct {
	value *GetPayoutCountries200ResponseData
	isSet bool
}

func (v NullableGetPayoutCountries200ResponseData) Get() *GetPayoutCountries200ResponseData {
	return v.value
}

func (v *NullableGetPayoutCountries200ResponseData) Set(val *GetPayoutCountries200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPayoutCountries200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPayoutCountries200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPayoutCountries200ResponseData(val *GetPayoutCountries200ResponseData) *NullableGetPayoutCountries200ResponseData {
	return &NullableGetPayoutCountries200ResponseData{value: val, isSet: true}
}

func (v NullableGetPayoutCountries200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPayoutCountries200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


